      <h1>Informations - Marathon des Deux Rives SSQ</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour le Marathon des Deux-Rives SSQ.
          <p align="Justify">
          Le 29 août 2010 se tiendra la 13e édition du Marathon des Deux Rives SSQ, l'événement sportif international le plus important de la 
          région de Québec et l'un des plus courus au Canada.<br><br>
          Le caractère distinctif du parcours réside dans le fait que près de 75% de l'action se déroule le long du fleuve St-Laurent, 
          offrant un aspect panoramique très marquant pour les participants. Le départ du Marathon et du Demi-marathon s'effectue sur 
          la Rive-Sud, les participants traversent le pont de Québec pour terminer dans le Vieux Québec.<br><br>
          Les épreuves offertes aux coureurs et aux marcheurs sont les suivantes :<br>
          - Marathon (42,2 km);<br>
          - Demi-marathon (21,1 km);<br>
          - 10 km;<br>
          - Course des Jeunes (5 km pour les 7 à 14 ans).<br><br>
          Il y a aussi une activité de financement pour un organisme dans le domaine de la santé : le 5 km de la Santé.
          </p>
          
           <p align="Justify"><b>Sites de départ</b><br>
           <b style="color:red">Marathon</b>: Le départ du marathon (42,2 km) se prend sur la rue Métivier à Lévis. (Centre des Congrès de Lévis, juste à coté de l'Hotel Four Point)<br><br>
           <b style="color:red">Demi-Marathon</b>: Le départ du Demi-marathon (21,1 km) se prend sur le chemin du Fleuve, au pied de la Côte Rouge, à Lévis, secteur Saint-Romuald.<br><br>
           <b style="color:red">10 km</b>: Le départ du 10 km se prend sur le boulevard Champlain au quai des Cageux, tout à coté du Centre d'accueil de la Promenade Samuel-de Champlain<br><br> 
           <b style="color:red">Course des jeunes et 5 km de la Santé</b>: Les départs de la Course des jeunes et du 5 km de la Santé se prennent au même endroit, soit sur le boulevard Champlain, au pied de la Côte Gilmour, à Québec.<br><br>
           </p>
          
        <p align="Justify">
          <b>Besoins du club</b><br>
          Le club a besoin de <b>30 à 40 personnes</b> pour couvrir cette activit&eacute;.<br>
          Notre tâche aura 2 volets:<br>
          <ol>
            <li>Suivre et indiquer aux responsables du marathon qui sont les meneurs et meneuses des divers groupes et leur passage à des endroits identifiés par ceux-ci.</li><br>
            <li>S'assurer que le parcours de course est libre de piétons et de cyclistes pendant l'activité. Accessoirement aider les bénévoles responsables de bloquer les rues à gérer la circulation automobile.</li>
          </ol>
          
          Nous avons besoin de 9 accompagnateurs pour le premier volet. Pour les autres membres qui baliseront le parcours, vous recevrez des coordonnées 
          de points départ des courses. Comme les départs sont tôt le matin, nous comptons sur votre présence ponctuelle aux heures indiquées pour chacuns des départs. 

          <!--
            L'objectif est de suivre les 3 premiers hommes et femmes de chacunes des catégories de coureurs et de sécuriser le parcours en v&eacute;lo sur le parcours des différentes activités du Marathon des Deux-Rives.
          --></p>
          <p align="Justify"><b>Lieu de rassemblement</b><br>
          <b>Pour le 42,2 KM et le 21KM</b>: Stationnement de la traverse de Lévis (coté Lévis) à 7H30<br>
          <b>Pour le 10 KM </b>: Stationnement de la cote Ross à 7h30<br>
          <b>Pour la course des jeunes et le 5 KM de la Santé</b>: Stationnement de la cote Ross à 7h15<br>
          </p>
         <p>Merci.        </p>
         
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       
        <form enctype='multipart/form-data' action='process2rives.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        <tr>
          <td>Parcours :<font color='#ff0000'>*</font></td>
          <td>
            <select name="Parcours">
              <option>Veuillez choisir</option>
              <option value="Marathon">Marathon : 42,2km - Départ à 7h30</option>
              <option value="Demi-Marathon">Demi-Marathon : 21,1km - Départ à 8h30</option>
              <option value="10Km">10km - Départ à 8h30</option>
              <option value="Course des jeunes">Course des jeunes - départ à 8h00</option>
              <option value="5KM de la santé">5km de la santé - départ à 8h00</option>
            </select>
          </td>
        </tr>
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
        </div>
       </div>  

    </div>
  