      <h1>Information - Randonn&eacute;e cycliste familiale LACINQ de Beauport</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>La randonn&eacute;e LACINQ aura lieu le <STRONG>dimanche 6 juin 2010</STRONG> (Beau temps, mauvais temps).&nbsp;</p>
          <p align="Justify">Le club a besoin de <STRONG>40 &agrave; 50 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          L'objectif est de sécuriser <a href="documents/Parcours_la5.jpg" target="_blank" style="color:red"><b>le parcours en v&eacute;lo</b></a> de 25 kilom&egrave;tres dans les rues de Beauport.<br>
			Le trajet est adapt&eacute; aux petites familles &agrave; une vitesse de 12 km/h avec l'aide des policiers de la Ville de Qu&eacute;bec.</p>
		<p align="Justify">Pour plus d'informations, consultez le <a href="http://www.rospab.ca/inscription" target="_blank"><b style="color:red">site Internet de LA CINQ</b></a></p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>&Eacute;cole secondaire Samuel-De-Champlain &agrave; 8h00.<br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
		</p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processcinq.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  