      <h1>Informations - Championnats du monde au Mont Sainte-Anne</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>Voici les informations pour les Championnats du monde qui aura leiu au Mont St-Anne les 30-31 ao&ucirc;t, 1, 2 et 3 septembre.</p>
		<p align="Justify">Le club a besoin de <STRONG>35 &agrave; 40 personnes </STRONG>pour couvrir cette activit&eacute;, durant ces 5 journ&eacute;es.</p>
		Voici les heures pour les quelles vous devrez &ecirc;tre disponibles pour s&eacute;curiser le parcours de cross-country :<br>
		<br>
		<strong>30 ao&ucirc;t : De 12h &agrave; 16h<br>
			31 ao&ucirc;t : De 8h &agrave; 16h<br>
			1 sept : De 7h &agrave; 16h<br>
			2 sept : De 8h &agrave; 15h30<br>
			3 sept : De 7h &agrave; 15h30<br>
		</strong><br>
		Vous devez remplir le <strong>formulaire BENEVOLE</strong> sur le site internet :
		<table width="260" border="0" cellspacing="2" cellpadding="3" bgcolor="#ed1b24">
			<tr height="20">
				<td width="260" height="20"><a href="http://www.gestev.com/benevoles/formulaire-dinscription" target="_blank"><strong>CLIQUEZ ICI POUR VOUS INSCRIRE</strong></a></td>
			</tr>
		</table>
		Et dans la case <strong>GROUPE</strong> : tr&egrave;s important d&rsquo;<strong>&eacute;crire SENTINELLES</strong>. &Eacute;galement joindre une photo .jpg avec leur formulaire, il y a un endroit au bas du formulaire pour &ccedil;a. (Les photos serviront pour les cartes d&rsquo;accr&eacute;ditations)<br>
		<strong>Date limite pour s&rsquo;inscrire, le 23 ao&ucirc;t.</strong>
		<p align="Justify">Confirmez &eacute;galement votre pr&eacute;sence dans le pr&eacute;sent formulaire en pr&eacute;cisant la journ&eacute;e ou vous serez pr&eacute;sents, pour que nous puissions transmettre &agrave; l&rsquo;organisation les noms des encadreurs pour chaque journ&eacute;e.</p>
		<p align="Justify"><br><b>Lieu de rassemblement</b><br>Mont Ste-Anne<br>
          <br>
          <b>Matériel à emporter avec vous</b><br>
          Chaise de camping<br>
          Eau<br>
          Huile à mouche<br>
          Vêtements en fonction de la température<br>
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
          Encadreurs responsables: à déterminer 
          </p>
		<b>Confirmer votre présence le plus tôt possible</b>    
      
      <br><br>
      
          <form enctype='multipart/form-data' action='processcountry.php' method='post'>
          <table border=0>
          <tr>
            <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Prenom' size=30></td></tr>
          <tr>
            <td> Nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Nom' size=30>
          <tr>
          <td> Journ&eacute;e:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Journee' size=30>
          </tr>
          <tr>
            <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
            <td><p>
              <label>
                <input type="radio" name="Present" value="Oui">
                Oui</label>
              <label>
                <input type="radio" name="Present" value="Non">
                Non</label>
            </p>
          </tr>
          </table><br>
       <br>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  