      <h1>Informations - Cyclo-Défi de Québec</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour le Cyclo-Défi de Québec.</p>
          <p align="Justify">Le club a besoin de <STRONG>30 à 40 personnes </STRONG>pour couvrir cette activit&eacute;.<br></p>
          <p align="Justify">
            Le Cyclo-Défi vous propose une randonnée cycliste des plus extraordinaires : départ et arrivée au site de l'ancien jardin zoologique situé 
            dans l'arrondissement Charlesbourg; deux parcours de 100 et 150 km dans la belle région de Portneuf; tous les services auxquels les 
            cyclistes s'attendent seront fournis.
          </p>
          <p align="Justify"><b>Lieu de rassemblement</b><br>
          Jardin Zoologique de Québec<br>
          (prendre la sortie Charlesbourg/St-Émile de l'autoroute 73 Nord) 
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br> 
          </p>
<p>
<br>
Voici les deux parcours proposés (subdivisés en 4 groupes) :
<br><br>

<table border="1" bordercolor="#888" cellspacing="0" style="border-bottom-color:#888;border-right-width:1px;border-top-color:#888;border-collapse:collapse;border-top-width:1px;border-bottom-width:1px;height:200px;border-right-color:#888;border-left-color:#888;border-left-width:1px">
<tbody>
<tr>
<td style="width:120px;height:26px">
<p style="text-align:center"><strong><font size="3"> Groupes</font></strong></p></td>
<td style="width:131px;height:26px">

<p style="text-align:center"><strong><font size="3"> Départ</font></strong></p></td>
<td style="width:109px;height:26px">
<p style="text-align:center"><strong><font size="3"> Dîner Ste-Catherine</font></strong></p></td>
<td style="width:172px;height:26px">
<p style="text-align:center"><strong><font size="3">Dîner  St-Raymond</font></strong></p></td>
<td style="width:152px;height:26px">
<p style="text-align:center"><strong><font size="3">Pause  Neuville</font></strong></p></td>
<td style="width:108px;height:26px">
<p style="text-align:center"><strong><font size="3"> Arrivée</font></strong></p></td></tr>
<tr>
<td style="width:120px;height:25px">
<p style="text-align:center">100 km ( 22 km/h )</p></td>

<td style="width:131px;height:25px">
<p style="text-align:center">9h45</p></td>
<td style="width:109px;height:25px">
<p style="text-align:center">11h15</p></td>
<td style="width:172px;height:25px">
<p style="text-align:center"> x</p></td>
<td style="width:152px;height:25px">
<p style="text-align:center">13h20</p></td>
<td style="width:108px;height:25px">
<p style="text-align:center">15h25</p></td></tr>
<tr>
<td style="width:120px;height:25px">

<p style="text-align:center">100 km ( 25 km/h )</p></td>
<td style="width:131px;height:25px">
<p style="text-align:center">10h30</p></td>
<td style="width:109px;height:25px">
<p style="text-align:center">11h50</p></td>
<td style="width:172px;height:25px">
<p style="text-align:center"> x</p></td>
<td style="width:152px;height:25px">
<p style="text-align:center">13h45</p></td>
<td style="width:108px;height:25px">
<p style="text-align:center">15h40</p></td></tr>

<tr>
<td style="width:120px;height:21px">
150 km ( 25 km/h )</td>
<td style="width:131px;height:21px;text-align:center">
<p>8h30</p></td>
<td style="width:109px;height:21px;text-align:center">
<p>10h50 (pause)</p></td>
<td style="width:172px;height:21px;text-align:center">
<p> 12h15</p></td>
<td style="width:152px;height:21px;text-align:center">
<p>14h10</p></td>
<td style="width:108px;height:21px;text-align:center">

<p>16h00</p></td></tr>
<tr>
<td style="width:120px;height:22px">
<p style="text-align:center">150 km ( 30 km/h )</p></td>
<td style="width:131px;height:22px;text-align:center">
<p> 8h15</p></td>
<td style="width:109px;height:22px;text-align:center">
<p>10h10 (pause)</p></td>
<td style="width:172px;height:22px;text-align:center">
<p>11h25</p></td>
<td style="width:152px;height:22px;text-align:center">
<p>13h05</p></td>

<td style="width:108px;height:22px;text-align:center">
<p>14h45</p></td></tr></tbody></table>
<br><br>
<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif"><strong>100 km</strong> : deux pelotons de 22 et 25 km/h</font></div>
<div><font face="verdana,sans-serif"> </font></div>

<div>
<div><font face="verdana,sans-serif">Départ / arrivée : 8191 Avenue Du Zoo, Charlesbourg, QC</font></div>
<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif">Dîner à Ste-Catherine-de-la-Jacques-Cartier</font></div>
<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif">Pause et ravitaillement à Neuville</font></div></div>
<div> </div>
<div>
<img border="0" width="664" height="400" src="http://www.cyclodefiquebec.com/_/rsrc/1257520801487/parcours/100_3.jpg" /></a></div>
<br><br>
<div style="text-align:left;display:block">
  <img border="0" width="685" height="220" src="http://www.cyclodefiquebec.com/_/rsrc/1257541677033/parcours/D%C3%A9nivel%C3%A9_100.JPG" />
</div>
<br><br><br><br>
<div><font face="verdana,sans-serif"><strong> </strong></font></div>
<div style="text-align:left;display:block"><font face="verdana,sans-serif"><strong>150 km</strong> : deux pelotons de 25 et 30 km/h</font></div>
<div style="text-align:left;display:block">
<div>

<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif">Départ / arrivée : 8191 Avenue Du Zoo, Charlesbourg, QC</font></div>
<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif">Dîner à St-Raymond</font></div>
<div><font face="verdana,sans-serif"> </font></div>
<div><font face="verdana,sans-serif">Pauses et ravitaillements à St-Catherine-de-la-Jacques-Cartier et Neuville</font></div></div></div>
<div style="text-align:left;display:block"><font face="verdana,sans-serif"> </font></div>
<div style="text-align:left;display:block"> </div>
<div style="text-align:left;display:block">
  <img border="0" src="http://www.cyclodefiquebec.com/_/rsrc/1257522024964/parcours/150_2.jpg" />
  <br><br>
  <img border="0" width="688" height="220" src="http://www.cyclodefiquebec.com/_/rsrc/1257541736204/parcours/D%C3%A9nivel%C3%A9_150.JPG" />
</div> 
<br><br>



         <br><br></div>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action='processdefiquebec.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        <tr>
          <td>Parcours :<font color='#ff0000'>*</font></td>
          <td>
            <select name="Parcours">
              <option>Veuillez choisir</option>
              <option value="100-22km/h">100 km ( 22 km/h )</option>
              <option value="100-25km/h">100 km ( 25 km/h )</option>
              <option value="150-25km/h">150 km ( 25 km/h )</option>
              <option value="150-30km/h">150 km ( 30 km/h )</option>
            </select>
          </td>
        </tr>
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  