
<link href="../style.css" rel="stylesheet" media="screen">
<script language="javascript">
	if (AC_FL_RunContent == 0) {
		alert("This page requires AC_RunActiveContent.js.");
	} else {
		AC_FL_RunContent(
			'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
			'width', '839',
			'height', '352',
			'src', 'entete',
			'quality', 'high',
			'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
			'align', 'middle',
			'play', 'true',
			'loop', 'false',
			'scale', 'showall',
			'wmode', 'window',
			'devicefont', 'false',
			'id', 'entete',
			'bgcolor', '#ffe49b',
			'name', 'entete',
			'menu', 'false',
			'allowFullScreen', 'false',
			'allowScriptAccess','sameDomain',
			'movie', 'entete',
			'salign', ''
			); //end AC code
	}
</script>
<noscript>
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="839" height="352" id="entete" align="middle">
	<param name="allowScriptAccess" value="sameDomain" />
	<param name="allowFullScreen" value="false" />
	<param name="movie" value="entete.swf" /><param name="loop" value="false" /><param name="menu" value="false" /><param name="quality" value="high" /><param name="bgcolor" value="#ffe49b" />	<embed src="entete.swf" loop="false" menu="false" quality="high" bgcolor="#ffffff" width="839" height="352" name="entete" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
	</object>
</noscript>

<div id="calendrier" style="z-index=10">
<img src="../images/picto_mois.gif" alt="" width="45" height="45" border="0">
<div class="menusnoir">
			  <span class="menusnoir">LES ACTIVIT&Eacute;S<br>
				  DE LA SAISON<br>
					<a href="../encadrements.php">&gt; Encadrements</a><br>
				  <a href="../sorties.php">&gt; Sorties</a></span>
</div>
</div>