      <h1>Information - Manifestation &agrave; v&eacute;lo &laquo; Faites-nous de la place !!! &raquo;</h1>
<DIV class="textes">
	<div style="margin-left:0px; margin-right:35px; text-align:left">
		<p>Bonjour amis Sentinelles,<br>
			<br>
		</p>
		<p><strong>Le samedi, 18 septembre, Acc&egrave;s transports viables fera la manifestation &agrave; v&eacute;lo &laquo; Faites-nous de la place !!! &raquo; pour d&eacute;montrer aux citoyens automobilistes que les cyclistes ont droit au respect sur les routes et qu&rsquo;il est possible et souhaitable que des infrastructures doivent &ecirc;tre pens&eacute;es et r&eacute;alis&eacute;es afin d&rsquo;assurer une place s&eacute;curitaire et efficace pour les cyclistes.</strong></p>
		<p>Les organisateurs inviteront les participants &agrave; signer une p&eacute;tition g&eacute;ante pour le d&eacute;veloppement d&rsquo;une piste cyclable sur les grandes art&egrave;res.<br>
			Suite &agrave; la signature, les participants et les encadreurs pourront, avec leur coupon remis au d&eacute;part, aller chercher 2 ou 3 &eacute;pis de bl&eacute; d'Inde ainsi qu&rsquo;un breuvage de leur choix aux endroits d&eacute;sign&eacute;s.<br>
			
			Sur place, les participants puissent verrouiller leur v&eacute;lo en toute s&eacute;curit&eacute;. Un c&acirc;ble d&rsquo;acier sera d&eacute;ploy&eacute; et les participants pourront barrer leur v&eacute;lo &agrave; ce fil. Sinon, on peut faire un p&eacute;rim&egrave;tre de s&eacute;curit&eacute; avec des cl&ocirc;tures afin d&rsquo;y mettre les v&eacute;los. Un ou deux b&eacute;n&eacute;voles surveilleront les v&eacute;los durant l&rsquo;activit&eacute;.</p>
		<p><strong>Nous aurons besoin de 10-12 encadreurs pour couvrir cet &eacute;v&eacute;nement.</strong></p>
		<p><strong>Le d&eacute;part se fera &agrave; 10h30 :<br>
				Stationnement P2 de l&rsquo;&eacute;cole secondaire </strong><a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=3643+Avenue+des+Compagnons,+Sainte-Foy,+Qu%C3%A9bec+G1X+3Z6&sll=49.891976,-97.399991&sspn=0.662648,1.027222&dirflg=r&ttype=dep&date=10%2F09%2F02&time=12:19&noexp=0&noal=0&sort=&ie=UTF8&hq=&hnear=3643+Avenue+des+Compagnons,+Sainte-Foy,+Communaut%C3%A9-Urbaine-de-Qu%C3%A9bec,+Qu%C3%A9bec+G1X+4V8&t=h&z=16" target="_blank"><font color="red"><strong>Les Compagnons de Cartier</strong></font></a><strong>, 3643 Avenue des Compagnons, Sainte-Foy<br>
				Nous vous demandons d&rsquo;&ecirc;tre l&agrave; vers 9h30.</strong>
		
		<p>Les encadreurs responsables seront Laurent Thivierge-Deslauriers et R&eacute;jean Cloutier.</p>
		<p>Merci !</p>
	</div>
				<br>
					<b>Confirmer votre pr&eacute;sence le plus t&ocirc;t possible</b>
					</DIV>
				<div class="textes">
					<form enctype="multipart/form-data" action="processfaitesplace.php" method="post">
						<table border=0>
							<tr>
								<td>Pr&eacute;nom:<font color="#ff0000">*</font></td>
								<td><input type=text name="Prenom" size=30></td>
							</tr>
							<tr>
								<td>Nom:<font color="#ff0000">*</font></td>
								<td><input type=text name="Nom" size=30></td>
							</tr>
							<tr>
								<td>Je serai pr&eacute;sent:<font color="#ff0000">*</font></td>
								<td>
									<p><label>
									<input type="radio" name="Present" value="Oui">
									Oui</label>
									<label>
									<input type="radio" name="Present" value="Non">
									Non</label>
									</p>
							</tr>
							
						</table><br>
						<div>
							<input type="submit" value="Envoyer">
							<input type=reset value="Effacer">
					</form>
				</div>
				<img src="documents/trajet_manifestation.jpg" alt="" width="600" height="438" border="0"></strong></p>
				</div>



  