      <h1>Information - Festiv&eacute;lo MEC</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
		<p>Bonjour amis Sentinelles,<br>
			<br>
			Le club a re&ccedil;u une invitation du Festiv&eacute;lo MEC de Qu&eacute;bec, qui se d&eacute;roulera le dimanche 23 mai 2010,<br>
			au lieu historique national Cartier-Br&eacute;beuf, &agrave; Qu&eacute;bec.</p>
		<p>Dans le cadre de cet &eacute;v&eacute;nement, les nouvelles banni&egrave;res promotionnelles des Sentinelles de la Route seront install&eacute;es<br>
			et nous ferons la promotion du club tout en distribuant les d&eacute;pliants de s&eacute;curit&eacute; &agrave; v&eacute;lo de la SAAQ.</p>
		<p>Nous aurions besoin d&rsquo;une dizaine de personnes pour cette journ&eacute;e qui d&eacute;butera &agrave; 10h00 (beau temps, mauvais temps).</p>
		<p>Selon le nombres d&rsquo;inscriptions, la journ&eacute;e pourra &ecirc;tre partag&eacute;e en deux blocs de deux &eacute;quipes.</p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>
			Emplacement du club au lieu historique national Cartier-Br&eacute;beuf<br>
			<br>
		</p>
		<p>Merci!</p>
         </div>   
         <br><br>
	<b>Confirmer votre pr&eacute;sence au plus tard le 21 mai</b></DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processfestivelomec.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  