<div style="margin-left:20px; margin-right:30px; text-align:left" class="textes">
 
   <STRONG>Formation :&nbsp;S&eacute;curit&eacute; et   encadrement  </STRONG>
    
  <p align="justify"><STRONG><U>Description</U></STRONG> : Samedi le&nbsp;8&nbsp;mai&nbsp;d&egrave;s 8h   aura lieu la formation d'encadreur&nbsp;obligatoire pour tout les membres des Sentinelles. Les&nbsp;nouveaux&nbsp;membres&nbsp;apprendront en quoi consiste le travail&nbsp;d'encadrement.   Les anciens membres pourront aider les nouveaux dans leur apprentissage et   donner un coup de main&nbsp;au formateur.</STRONG></p>

  <p align="justify"><STRONG><U>Endroit</U></STRONG> :&nbsp;<font color="Red">Centre communautaire Michel Labadie, salle Polyvalente (RC-08), situé au 3705 Chauveau, Qc.</font></STRONG></p>
  <p align="justify"><STRONG><U>Important</U></STRONG> : La   formation d&eacute;butera par une partie th&eacute;orique qui <U>aura lieu sans &eacute;gard &agrave; la   temp&eacute;rature</U> puisque nous avons lou&eacute; un local. Nous aurons un endroit pour ranger les v&eacute;los pour ceux qu'il n'est pas s&eacute;curis&eacute;   sur leur voiture.</STRONG></p>

  <p align="justify"><STRONG><U>Quoi   apporter</U></STRONG> :&nbsp;Votre v&eacute;lo, <U>maillot&nbsp;et dossard   des Sentinelles pour ceux qui les ont</U>,&nbsp;&nbsp;tenue pour   rouler,&nbsp;crayon, papier&nbsp;et un lunch&nbsp;froid pour le   d&icirc;ner.</STRONG></p>
  <p align="justify"><STRONG>Informations sur le   cours</STRONG> :<BR>

    -&nbsp;Un document de   formation&nbsp;vous sera remis sur   place.<BR>
      -   La   formation sera divis&eacute;e en 2 parties ;<BR>
        -&nbsp;Premi&egrave;re&nbsp;partie&nbsp;&agrave;   9h :&nbsp;th&eacute;orique portant   sur les r&ocirc;les et responsabilit&eacute;s de l'encadreur, le code d'&eacute;thique et le code de   la route.<BR>

          -&nbsp;Deuxi&egrave;me&nbsp;partie*&nbsp;vers 11h30   : pratique&nbsp;en v&eacute;lo&nbsp;sur   les techniques&nbsp;d'encadrement sur   route.&nbsp;<BR>
            - La formation devrait se terminer vers   14h.<BR>
              <BR>
                * S'il pleut   abondamment au moment de d&eacute;buter&nbsp;la 2e partie, une d&eacute;cision sera prise alors   pour d&eacute;terminer&nbsp;la tenue ou non de cette partie   pratique.</STRONG></p>

  <p><STRONG>Je vous attend donc pour cette formation&nbsp;IMPORTANTE pour chacun et chacune de   vous! </STRONG></p>
  <p><STRONG>Jean-Pierre Laforest, Pr&eacute;sident <BR>
  </STRONG></p>
          
    <BR clear="all">
    <p><STRONG><BR>
  </STRONG></p>

</DIV>
