      <h1>Informations - Randonnée cycliste du Festival Lorettain</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour la Randonnée cycliste du Festival Lorettain.</p>
          <p align="Justify">Le club a besoin de <STRONG>10 à 15 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          L'objectif est de sécuriser le <a style="color:red;" href="http://www.lancienne-lorette.org/medias/pdf/plan-velorette-2010.pdf" target="_blank"><b>parcours</b></a> en v&eacute;lo dans les rues de l'Ancienne-Lorette. 
          </p>
		<p align="Justify">Le d&eacute;part de la randonn&eacute;e est &agrave; 9h00 et nous vous demandons d&rsquo;arriver vers 8h00.</p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>
          Polyvalente de l'Ancienne-Lorette<br>
          1801, rue NOTRE-DAME<br>L'Anncienne-Lorette<br>
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br></p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action='processlorettain.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  