      <h1>Informations - Randonn&eacute;e Lotbini&egrave;re</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
		<p>Bonjour amis Sentinelles,<br>
			<br>
			Le 19 septembre prochain aura lieu la 6e &eacute;dition de la Randonn&eacute;e Lotbini&egrave;re.</p>
		<p align="justify"><strong>Nouveaut&eacute; cette ann&eacute;e !</strong><br>
			L&rsquo;organisation a ajout&eacute; une vitesse au parcours Tourisme Lotbini&egrave;re de (79 km), qui est maintenant disponible &agrave; 27 km/h.</p>
		<p align="justify"><strong>Nouveau point de rassemblement</strong><br>
			Comme les matins de septembre sont plut&ocirc;t froids, l&rsquo;organisation offre cette ann&eacute;e un accueil au chaud ! <strong>Le nouveau point de rassemblement est &agrave; l'&eacute;cole secondaire Beaurivage &agrave; Saint-Agapit</strong>. Le repas du midi sera &eacute;galement donn&eacute; dans cet &eacute;tablissement.</p>
		<p align="justify"><strong>Comment s&rsquo;y rendre :<br>
			</strong><strong>De Qu&eacute;bec</strong><br>
			Autoroute 20 ouest, sortie 291; <br>
			Direction route 273 sud (environ 9 km);<br>
			Au village de Saint-Agapit, tournez &agrave; droite sur la rue Du Centenaire (1134 Du Centenaire).<br>
			<strong>De Saint-Nicolas (L&eacute;vis)</strong><br>
			Route 116 ouest jusqu'au village de Saint-Agapit; <br>
			Tournez &agrave; droite &agrave; la lumi&egrave;re;<br>
			Tournez ensuite sur la 2e rue &agrave; droite (1134 Du Centenaire).</p>
		<p align="justify"><strong>Le rassemblement se fera d&egrave;s 8h00.</strong></p>
		<p align="justify"><strong>Heures des d&eacute;parts</strong><br>
			1- Maison de la famille (20 km) - 12 km/h : 10h00 <br>
			2- Desjardins (45 km) - 18 km/h : 9h50 <br>
			3- Tourisme Lotbini&egrave;re (79 km) - 24 km/h : 9h40<br>4- Tourisme Lotbini&egrave;re (79 km) - 27 km/h : 9h30<br>5- MRC de Lotbini&egrave;re (101 km) - 30 km/h : 9h20<br>
			<a href="http://www.lotbiniereavelo.com/randonnee/parcours.php" target="_blank"><font color="red">Vous pouvez t&eacute;l&eacute;charger les cartes des diff&eacute;rents parcours</font></a></p>
		<p align="justify">Nous avons besoin de 50 encadreurs (soit 10 par groupe).<br>
			Lors de votre inscription veuillez indiquer quel parcours vous d&eacute;sirez encadrer.</p>
		<p align="justify">Certaines contraintes pourront nous oubliger &agrave; d&eacute;placer quelques personnes.<br>
			Nous vous remercions de votre compr&eacute;hension habituelle.</p>
		<p align="justify">Vous recevrez donc les directives finales pour la distribution des postes, lors du rassemblement.</p>
		<p align="justify">Au plaisir de vous voir nombreux pour cet &eacute;v&eacute;nement.</p>
		<br>
		<b>Confirmer votre présence le plus tôt possible</b>    
       </div></DIV>
       <div class="textes" style="margin-left:20px; margin-right:35px; text-align:left">
        <form enctype='multipart/form-data' action="processlotbiniere.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        <tr>
          <td>Parcours :<font color='#ff0000'>*</font></td>
          <td>
            <select name="Parcours">
              <option>Veuillez choisir</option>
              <option value="20km">Trajet de 20 km (vitesse moyenne : 12 km/h)</option>
              <option value="45Km">Trajet de 45 km (vitesse moyenne : 18 km/h)</option>
              <option value="79Km-24h">Trajet de 79 km (vitesse moyenne : 24 km/h)</option>
              <option value="79Km-27h">Trajet de 79 km (vitesse moyenne : 27 km/h)</option>
              <option value="101km">Trajet de 101 km (vitesse moyenne : 30 km/h)</option>
            </select>
          </td>
        </tr>
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  