      <h1>Information - Marche de la mémoire RONA</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Notre troisième encadrement arrive bient&ocirc;t, soit <STRONG>dimanche le 30 mai 2010</STRONG>. Il s'agit du&nbsp;<STRONG>Marche de la mémoire Rona</STRONG>. </p>
          <p align="Justify">Le club a besoin de <STRONG>20 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          L'objectif est de sécuriser <a href="documents/memoire_RONA.pdf" target="_blank" style="color:red"><b>le parcours en v&eacute;lo</b></a> sur les Plaines d'Abraham ainsi que que sur l'avenue de la Grande-Allée avec l'aide des policiers de la Ville de Québec.</p>
          <p align="Justify"><b>Lieu de rassemblement</b><br>
          Centre d'accueil situé coin Boulevard Georges VI et Boulevard Ontario sur les Plaines à 8H30.<br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br> 
          L'activit&eacute; se terminera par un dîner Hot dogs. </p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action='processmemoire.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  