      <h1>Information - Mini-tours pour la Fondation Charles Bruneau</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>Le Mini-tours aura lieu le <STRONG>samedi 12 juin 2010</STRONG>.&nbsp;</p>
		<p align="Justify">Le club a besoin de <STRONG>10-12 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
			Depart vers 10h00-10h30 du IGA Lac Beauport et arrivee au m&ecirc;me endroit vers 11h30-12h00.<br>
			Le parcours est d'environ 15 km.<br>
			Nous attendons environ 125 personnes.</p>
		<p align="Justify">Pour plus d'informations, consultez le <a href="http://www.charlesbruneau.qc.ca/tour-cibc/fr/cibc/mini-tours.php" target="_blank"><b style="color:red">site Internet du Mini-tours</b></a></p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>IGA Lac Beauport.<br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
		</p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processminitours.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  