      <h1>Informations - Raid Vélo Mag</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour le Raid Vélo Mag qui aura lieu pendant le Vélirium au Mont St-Anne.</p>
          <p align="Justify">Le club a besoin de <STRONG>35 à 40 personnes </STRONG>pour couvrir cette activit&eacute;. Le but de cette activité 
          est de sécuriser les intersections le temps du passsge des coureurs. C'est une activité extra rapide qui ne dure qu'au maximum 15 minutes.  
          Par la suite, nous pourrons nous diriger vers le Camping Municipal de Beauport pour notre party annuel. 
          </p>
          <p align="Justify"><br><b>Lieu de rassemblement</b><br>
          Stationnement du Domaine Maizeret à 9h00 AM<br>
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
          Encadreurs responsables: à déterminer 
          </p>
         <b>Confirmer votre présence le plus tôt possible</b>    
      
      <br><br>
      
          <form enctype='multipart/form-data' action='processvelirium.php' method='post'>
          <table border=0>
          <tr>
            <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Prenom' size=30></td></tr>
          <tr>
            <td> Nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Nom' size=30>
          </tr>
          <tr>
            <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
            <td><p>
              <label>
                <input type="radio" name="Present" value="Oui">
                Oui</label>
              <label>
                <input type="radio" name="Present" value="Non">
                Non</label>
            </p>
          </tr>
          </table><br>
       <br>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  