      <h1>Information - La Descente Royale Desjardins</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>La Descente Royale Desjardins aura lieu le <STRONG>dimanche 6 juin 2010</STRONG> (Beau temps, mauvais temps).&nbsp;</p>
          <p align="Justify">Le club a besoin de <STRONG>4 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          L'objectif est de sécuriser <a href="includes/documents/memoire_RONA.pdf" target="_blank" style="color:red"><b>en v&eacute;lo le parcours des coureurs</b></a> durant les 5 premiers kilom&egrave;tres, longe la rivi&egrave;re Montmorency du nord au sud, et les 5 derniers kilom&egrave;tres sur l'avenue Royale et le boulevard des Chutes. L'arriv&eacute;e se fera au Centre sportif Marcel-B&eacute;dard.</p>
		<p align="Justify">Pour plus d'informations, consultez le <a href="http://www.marathonquebec.com/sites/royale-html/generales.html" target="_blank"><b style="color:red">site Internet de la Descente Royale Desjardins</b></a></p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>
			Centre sportif Marcel-B&eacute;dard, 655, boulevard des Chutes, Beauport, &agrave; 8h00.<br>
			<br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
		</p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processroyale.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  