      <h1>Information - Revitalisation Village Saint-Nicolas</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
		<p>Bonjour amis Sentinelles,<br>
			<br>
		</p>
		<p>Le groupe Revitalisation Village Saint-Nicolas organise pour une deuxi&egrave;me ann&eacute;e une randonn&eacute;e de v&eacute;lo qui a pour but de faire d&eacute;couvrir des commer&ccedil;ants et des producteurs mara&icirc;chers de la r&eacute;gion.</p>
		<p>&nbsp;Celle-ci est une randonn&eacute;e familiale limit&eacute;e &agrave; 200 participants.&nbsp; C&rsquo;est une randonn&eacute;e de 22,5 Km &agrave; une vitesse moyenne de 12 Km/h.&nbsp; 4 arr&ecirc;ts &#150; Cidrerie St-Nicolas, Ferme Genest, &Eacute;tang de p&ecirc;che Berni&egrave;res, Ferme Gosselin &#150; sont pr&eacute;vus, avec environ 5 Km entre chacun.</p>
		<p>Nous aurons donc besoin de 14 &agrave; 16 encadreurs pour cette activit&eacute;.&nbsp; </p>
		<p>Pour ceux et celles qui voudraient y faire des achats, il vous sera possible de d&eacute;poser vos achats dans l&rsquo;autobus et de les r&eacute;cup&eacute;rer &agrave; l&rsquo;arriv&eacute;e.</p>
		<p>Si quelques personnes pouvaient apporter leur pompe de v&eacute;lo, il y aura s&ucirc;rement des pneus &agrave; gonfler avant le d&eacute;part.</p>
		<p align="Justify"><strong>Le d&eacute;part se fera de la Maison du Citoyen, 1365 Route Marie-Victorin &agrave; Saint-Nicolas, &agrave; compter de 9h00 et le retour vers 12h15.</strong></p>
		<p align="Justify">Les encadreurs responsables seront H&eacute;l&egrave;ne Poulin et Daniel Demers.</p>
		<p>Merci !</p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processsaintnicolas.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  