      <h1>Information - Tour du silence</h1>
      <DIV class="textes">
          <p>Notre deuxi&egrave;me encadrement de la saison aura lieu &nbsp;mercredi le <strong>19 mai 2010</strong>.<br>
		Il s'agit du <strong>Tour du silence (</strong>anciennement Randonn&eacute;e du silence<strong>)</strong>.</p>   
          <p>Le club a besoin d'au moins <strong>20 encadreurs </strong>pour couvrir   cette activit&eacute;.   
          L'objectif est d'effectuer l'encadrement d'un peloton de 200 &agrave;   300 cyclistes dans les rues de la belle ville de Qu&eacute;bec (arrondissement de   Ste-Foy). Il s'agit d'un parcours facile de 11 km &agrave; une vitesse de 12 &agrave; 15 km/h   qui <strong>aura lieu peu importe la temp&eacute;rature</strong>.   
          Cette randonn&eacute;e qui en est &agrave; sa 5e &eacute;dition, a toujours lieu le   3e mercredi de mai et ce, &agrave; la grandeur de l'am&eacute;rique du nord. Appuy&eacute;e d'une   couverture m&eacute;diatique, elle comm&eacute;more les cyclistes qui ont &eacute;t&eacute; bless&eacute;s ou tu&eacute;s   lors de la pratique de leur sport sur les voies publiques.</p> 
          
          <p>Pour plus d'informations, consultez le <a href="http://www.fqsc.net/cyclosportif/tour-du-silence-edition-2010" target="_blank"><b style="color:red">site Internet</b></a>   
          <p><b>Lieu de rassemblement</b><br>Stationnement au sud du stade de football du Peps de l'Universit&eacute; Laval &agrave; 18h15. </p>
          <p><b>Pour s&rsquo;y  rendre&nbsp;:</b><br>Autoroute Robert-Bourassa direction Sud, sortie De l&rsquo;Universit&eacute;,<br>
          Suivre la courbe (passage sur le viaduc de Robert-Bourassa),<br>
          Continuer tout  droit (direction Est) &agrave; l&rsquo;intersection,<br>
          le stationnement est derri&egrave;re la cabane  &laquo;&nbsp;Bud &raquo;.</p>
          
          <p>Les directives et la   distribution des postes se feront &agrave; ce moment. L'activit&eacute; se terminera vers   20h30. </p>
          <p><u>Bienvenue  &agrave; tous les nouveaux membres pour apprendre &agrave; encadrer!</u></p>
          <b>IMPORTANT : Confirmez votre pr&eacute;sence d&egrave;s&nbsp;que possible</b><br>
          Merci &agrave; l'avance pour   votre collaboration et au plaisir de vous revoir! </p>
       </DIV>
       <br>
       <div class="textes">
        <form enctype='multipart/form-data' action='processsilence.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  