      <h1>Informations - Randonnée pour la prévention du suicide</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour la Randonnée pour la prévention du suicide.</p>
          <p align="Justify">Le club a besoin de <STRONG>50 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          L'objectif est de sécuriser les 3 parcours en v&eacute;lo, subdivisés en 5 catégories, suivants dans les rues de Bellechasse : 
          <ul>
            <li><b style="color:red">Élite</b> : 96 km à 30km/h - Départ à 8h30<br></li>
            <li><b style="color:red">Inter-Élite</b> : 96km à 25 km - Départ à 8h45<br></li>
            <li><b style="color:red">Inter</b> : 58 km à 22km/h - Départ à 9h00<br></li>
            <li><b style="color:red">Familial - Adulte</b> : 30 km à 18 km / h - départ à 9h15<br></li> 
            <li><b style="color:red">Familiale avec enfants</b> : 30 km à 15 km / h <br></li>
          </ul>
          </p>
          
          <p align="Justify"><b>Lieu de rassemblement</b><br>
          Polyvalente de Saint-Anselme<br>
          825 route Bégin, St-Anselme<br>
          (prendre la sortie Pintendre/Lac-Etchemin de l'autoroute 20, continuer sur la 277) 
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br> 
          L'activit&eacute; se terminera par un dîner Hot dogs comme les années passées. </p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action='processsuicide.php' method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        <tr>
          <td>Parcours :<font color='#ff0000'>*</font></td>
          <td>
            <select name="Parcours">
              <option>Veuillez choisir</option>
              <option value="Elite">Élite : 96 km à 30km/h - Départ à 8h30</option>
              <option value="Inter-elite">Inter-Élite : 96km à 25 km - Départ à 8h45</option>
              <option value="Inter">Inter : 58 km à 22km/h - Départ à 9h00</option>
              <option value="Familiale-Adulte">Familial - Adulte : 30 km à 18 km / h - départ à 9h15</option>
              <option value="Familiale-Enfants">Familial avec enfants : 30 km à 15 km / h - Départ à 9h30</option>
            </select>
          </td>
        </tr>
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  