      <h1>Information - Randonn&eacute;e Tanguay</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>La randonn&eacute;e Tanguay aura lieu le <STRONG>dimanche 20 juin 2010</STRONG>.&nbsp;</p>
          <p align="Justify">Le club a besoin de <STRONG>40 &agrave; 50 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
			L'objectif est de s&eacute;curiser le parcours dans les rues de Qu&eacute;bec, avec l'aide des policiers de la Ville de Qu&eacute;bec.<br>
			De 1500 &agrave; 2000 participants sont attendus &agrave; cet &eacute;v&eacute;nement.</p>
		<p align="Justify">Pour plus d'informations, consultez le <a href="http://www.fondationmauricetanguay.com/randonnee_cycliste.htm" target="_blank"><b style="color:red">site Internet de la Randonn&eacute;e Tanguay</b></a></p>
		<p align="Justify"><b>Lieu de rassemblement</b><br>Stationnement du Colis&eacute; Pepsi &agrave; 8h00.<br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
		</p>
         <p>Merci.        </p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processtanguay.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  