      <h1>Information - Tour de Beauce</h1>
      <DIV class="textes">
        <div style="margin-left:0px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>L&rsquo;&eacute;tape de Qu&eacute;bec du Tour de Beauce aura lieu le <STRONG>samedi 19 juin 2010</STRONG> (Beau temps, mauvais temps).&nbsp;</p>
		<p align="Justify">Votre participation est importante pour le club, car c&rsquo;est une activit&eacute; qui demande 90 encadreurs.</p>
		<p align="Justify">Notre mandat est de s&eacute;curiser des intersections situ&eacute;es sur le parcours de cette comp&eacute;tition cycliste tr&egrave;s spectaculaire.</p>
		<p align="Justify">Inclus :  chandail ouat&eacute; avec capuchon aux couleurs du Tour de Beauce.</p>
		<p align="Justify">Pour plus d&rsquo;informations, consultez le <a href="http://2009.tourdebeauce.com/fr/site.asp?page=element&nIDElement=1062" target="_blank"><b style="color:red">site du Tour de Beauce</b></a></p>
		<p align="Justify"><b>Le lieu et l&rsquo;heure de rassemblement sont &agrave; confirmer</b><br>
			
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
		</p>
         <p>Merci!</p>
         </div>   
         <br><br>
         <b>Confirmer votre présence le plus tôt possible</b>    
       </DIV>
       <div class="textes">
        <form enctype='multipart/form-data' action="processtourbeauce.php" method='post'>
        <table border=0>
        <tr>
          <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Prenom' size=30></td></tr>
        <tr>
          <td> Nom:<font color='#ff0000'>*</font></td>
          <td>
        <input type=text name='Nom' size=30>
        </tr>
        <tr>
          <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
          <td><p>
            <label>
              <input type="radio" name="Present" value="Oui">
              Oui</label>
            <label>
              <input type="radio" name="Present" value="Non">
              Non</label>
          </p>
        </tr>
        
        </table><br>
        <div>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  