      <h1>Informations - Grande Vir&eacute;e-V&eacute;lo de l'Association des Implant&eacute;s Cochl&eacute;aires</h1>
      <DIV class="textes">
        <div style="margin-left:20px; margin-right:35px; text-align:left">
          <p>Bonjour amis Sentinelles,<br><br>
          Voici les information pour la Grande virée-vélo de l'AICQ.</p>
          <p align="Justify">Le club a besoin de <STRONG>20 à 30 personnes </STRONG>pour couvrir cette activit&eacute;.<br>
          La Grande Virée-Vélo vous propose une randonnée cycliste intéressante dans la belle région de Bellechasse.   
          </p>
          <p align="Justify"><b>Lieu de rassemblement</b><br>
          Aréna de St-Henri<br>
          (prendre la sortie Pintendre/Lac Etchemin de l'autoroute 20 Est) 
          <br><br>
          Les directives et la distribution des postes se feront &agrave; ce moment.<br>
          Encadreurs responsables: Guy Bordeleau et Réjean Cloutier 
          </p>
		<p align="Justify">Le premier d&eacute;part pour le 55 km est &agrave; 9h30 et nous vous demandons d&rsquo;&ecirc;tre l&agrave; vers 8h30.<br>
			Le d&eacute;part pour le 23 km est &agrave; 10h00.<br>
			Le d&eacute;part pour le 5 km est &agrave; 10h30.</p>
		<p>
          <br>
          Voici les trois parcours proposés :
          <br>
		<ul>
            <li><a style="color:red;font-weight:bold" href="documents/55.png" target="_blank">Randonnée Aventure</a>: 55KM @ 23km\h (St-henri à Ste-Claire)</li><br>
            <li><a style="color:red;font-weight:bold" href="documents/23.png" target="_blank">Randonnée Intermédiaire</a> : ± 23km  @ 18km\h (Région de St-Henri)</li><br>
            <li><a style="color:red;font-weight:bold" href="documents/famille.pdf" target="_blank">Randonnée Familiale</a>: ± 5km @ 12km\h</li><br>
          </ul>
               
         <b>Confirmer votre présence le plus tôt possible</b>    
          <br><br>
          <form enctype='multipart/form-data' action='processvireevelo.php' method='post'>
          <table border=0>
          <tr>
            <td> Pr&eacute;nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Prenom' size=30></td></tr>
          <tr>
            <td> Nom:<font color='#ff0000'>*</font></td>
            <td>
          <input type=text name='Nom' size=30>
          </tr>
          <tr>
            <td> Je serai pr&eacute;sent:<font color='#ff0000'>*</font></td>
            <td><p>
              <label>
                <input type="radio" name="Present" value="Oui">
                Oui</label>
              <label>
                <input type="radio" name="Present" value="Non">
                Non</label>
            </p>
          </tr>
          <tr>
            <td>Parcours :<font color='#ff0000'>*</font></td>
            <td>
              <select name="Parcours">
                <option>Veuillez choisir</option>
                <option value="Randonnée Aventure">Randonnée Aventure: 55KM @ 25km\h</option>
                <option value="Randonnée Intermédiaire">Randonnée Intermédiaire : ± 23km  @ 18km\h</option>
                <option value="Randonnée Familiale">Randonnée Familiale: ± 5km @ 12km\h</option>
              </select>
            </td>
          </tr>
          </table><br>
        <br>
          <input type='submit' value='Envoyer'> 
          <input type=reset value='Effacer'>
        </form>
      </div>

    </div>
  