<link href="../style.css" rel="stylesheet" media="screen">
<h1>Les Sentinelles de la Route vous souhaitent la bienvenue<h1>
<table width="64" border="0" cellspacing="0" cellpadding="0" align="right">
				<tr>
					<td><img src="images/logo_saaq.jpg" alt="" width="250px" align="right" border="0"></td>
				</tr>
			</table>
<script language="javascript">
	if (AC_FL_RunContent == 0) {
		alert("This page requires AC_RunActiveContent.js.");
	} else {
		AC_FL_RunContent(
			'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
			'width', '500',
			'height', '330',
			'src', 'photos',
			'quality', 'high',
			'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
			'align', 'middle',
			'play', 'true',
			'loop', 'true',
			'scale', 'showall',
			'wmode', 'opaque',
			'devicefont', 'false',
			'id', 'photos',
			'bgcolor', '#ffffff',
			'name', 'photos',
			'menu', 'true',
			'allowFullScreen', 'false',
			'allowScriptAccess','sameDomain',
			'movie', 'photos',
			'salign', ''
			); //end AC code
	}
</script>
						</p>
		<noscript>
							<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="500" height="330" id="photos" align="middle">
								<param name="allowScriptAccess" value="sameDomain">
								<param name="allowFullScreen" value="false">
								<param name="movie" value="photos.swf">
								<param name="quality" value="high">
								<param name="bgcolor" value="#ffffff">
								<param name="wmode" value="opaque">
								<embed src="photos.swf" quality="high" wmode="opaque" bgcolor="#ffffff" width="500" height="330" name="photos" align="middle" allowscriptaccess="sameDomain" allowfullscreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">
							</object>
						</noscript>
		<div class="textes">

<p>
<span style="font-size: 16px;">Bienvenue sur le site des <b style="color:red;">Sentinelles de la Route</b></span><br /><br />
			<p>Les <b style="color:red">Sentinelles</b><b style="color:red"> de la Route</b>
est un organisme sans but lucratif dont la mission principale est
d&rsquo;offrir un service d&rsquo;encadrement professionnel aux
organisateurs de randonn&eacute;es cyclistes de la grande
r&eacute;gion de Qu&eacute;bec.<br>
				<br>
			</p>
			<p>Le
Club a &eacute;galement comme mission de favoriser la pratique
s&eacute;curitaire des sports et particuli&egrave;rement les
activit&eacute;s cyclistes. Il est donc naturel que le port du
casque soit au c&#x0153;ur de nos pr&eacute;occupations.<br>
				<br>
			</p>
			<p>De plus, par l&rsquo;implication b&eacute;n&eacute;vole de ses membres, les <b style="color:red">Sentinelles</b><b style="color:red"> de la Route</b>
se donnent comme mission de venir en aide &agrave; la bonne
r&eacute;alisation de randonn&eacute;es cyclistes et autres
&eacute;v&eacute;nements aux b&eacute;n&eacute;fices
d&rsquo;&#x0153;uvres de bienfaisance ou de sport amateur.</p>
		</div>



	

	