
<link href="../style.css" rel="stylesheet" media="screen">
<h1>Le code d&rsquo;&eacute;thique des encadreurs des Sentinelles de la Route</h1>
<div class="textes">
	<p>
		Les actions que l&rsquo;encadreur cycliste pose, dans le cadre de ses activit&eacute;s, sont des actes professionnels.&nbsp; Que vous soyez employ&eacute;s ou b&eacute;n&eacute;voles pour une organisation, vous vous devez d&rsquo;avoir une attitude responsable digne de la fonction d&rsquo;encadreur cycliste.&nbsp; C&rsquo;est pour baliser le travail en encadrement cycliste que Les <b style="color:red">Sentinelles</b> de la <b>Route</b> vous soumet le pr&eacute;sent code d&rsquo;&eacute;thique.</p>
	<p><br>
		<b>L&rsquo;encadreur cycliste doit&nbsp;:</b>
		<li style="padding-top:0px;text-align:justify">Avoir &agrave; c&oelig;ur,  d&rsquo;abord et avant tout, l&rsquo;int&eacute;r&ecirc;t des participants des activit&eacute;s dont il est le  responsable.</li>
            <li style="padding-top:10px;text-align:justify">Prendre les  moyens pour faire respecter et appliquer de mani&egrave;re hi&eacute;rarchique, les grandes  priorit&eacute;s de l&rsquo;encadrement de groupe en plein air, &agrave; savoir&nbsp;: la s&eacute;curit&eacute;,  le confort, l&rsquo;agr&eacute;ment et/ou l&rsquo;apprentissage des participants.</li>
            <li style="padding-top:10px;text-align:justify">Poss&eacute;der toutes ses  capacit&eacute;s mentales et physiques lors des activit&eacute;s.</li>
            <li style="padding-top:10px;text-align:justify">Agir de mani&egrave;re  courtoise, franche et respectueuse dans ses approches et ses contacts avec les  participants et les autres responsables des activit&eacute;s encadr&eacute;es.</li>
            <li style="padding-top:10px;text-align:justify">Employer un  langage respectueux dans les communications verbales ou &eacute;crites.</li>
            <li style="padding-top:10px;text-align:justify">Respecter les  comp&eacute;tences, les domaines d&rsquo;expertise et les opinions des autres responsables  des activit&eacute;s encadr&eacute;es.</li>
            <li style="padding-top:10px;text-align:justify">R&eacute;gler en priv&eacute;  les diff&eacute;rents qui pourraient l&rsquo;opposer aux autres responsables et/ou aux  participants des activit&eacute;s encadr&eacute;es.</li>
            <li style="padding-top:10px;text-align:justify">Se conformer (son  v&eacute;lo aussi, ex&nbsp;: r&eacute;flecteurs sur roues) au code de la s&eacute;curit&eacute; routi&egrave;re.</li>
            <li style="padding-top:10px;text-align:justify">Avoir tout  l&rsquo;&eacute;quipement de s&eacute;curit&eacute; n&eacute;cessaire et recommand&eacute; afin de bien accomplir ses  t&acirc;ches.</li>
            <li style="padding-top:10px;text-align:justify">Avoir un v&eacute;lo et  des accessoires en excellente condition lors des activit&eacute;s.</li>
            <li style="padding-top:10px;text-align:justify">Faire appliquer,  &agrave; la lettre, aux participants le code de s&eacute;curit&eacute; routi&egrave;re et tous les  r&egrave;glements propres &agrave; l&rsquo;activit&eacute; encadr&eacute;e.</li>
            <li style="padding-top:10px;text-align:justify">Conna&icirc;tre  parfaitement les diff&eacute;rents sc&eacute;narios des man&oelig;uvres sur route.&nbsp; </li>
            <li style="padding-top:10px;text-align:justify">Favoriser  l&rsquo;harmonie entre les participants en d&eacute;veloppant un climat bas&eacute; sur l&rsquo;entraide,  le respect des diff&eacute;rences et des capacit&eacute;s de chacun.</li>
            <li style="padding-top:10px;text-align:justify">&Ecirc;tre disponible  pour aider, conseiller et secourir les participants lors des activit&eacute;s.</li>
            <li style="padding-top:10px;text-align:justify">Tenter de  pr&eacute;venir les &eacute;ventuels probl&egrave;mes (m&eacute;caniques, physiques, de d&eacute;placement) en  observant et conseillant continuellement les participants lors des activit&eacute;s  (ex&nbsp;: v&eacute;rification des v&eacute;los des participants avant le d&eacute;part).</li>
            <li style="padding-top:10px;text-align:justify">Avoir des  relations strictement professionnelles avec les participants des activit&eacute;s.</li>
            <li style="padding-top:10px;text-align:justify">Assumer la  responsabilit&eacute; de suivre les formations n&eacute;cessaires &agrave; la r&eacute;alisation de ses  t&acirc;ches.&nbsp; </li>
            <li style="padding-top:10px;text-align:justify">Tenir &agrave; jour ses  comp&eacute;tences dans les domaines propres &agrave; l&rsquo;encadrement cycliste (ex&nbsp;: notions  de secourisme).</li>
            <li style="padding-top:10px;text-align:justify">Agir avec un esprit  de collaboration et d&rsquo;appui mutuel avec les autres responsables des activit&eacute;s  auxquelles il participe.</li>
            <li style="padding-top:10px;text-align:justify">Se faire le  porte-parole et donner l&rsquo;exemple sur tous les aspects d&rsquo;un comportement  cycliste responsable.</li>
            <li style="padding-top:10px;text-align:justify">Tenir compte des  limites de ses comp&eacute;tences afin de n&rsquo;assumer que des t&acirc;ches pour lesquelles  l&rsquo;encadreur a la formation ad&eacute;quate.</li>
            <li style="padding-top:10px;text-align:justify">Recourir aux  ressources humaines et mat&eacute;rielles disponibles en cas de probl&egrave;me.</li>
            <li style="padding-top:10px;text-align:justify">Traiter  &eacute;quitablement tous les participants lors des activit&eacute;s encadr&eacute;es, peu importe  leurs conditions personnelles et ainsi pr&eacute;venir, &eacute;viter et corriger toutes  formes de discrimination.</li>
            <li style="padding-top:10px;text-align:justify">Traiter les  donn&eacute;es personnelles des participants de mani&egrave;re confidentielle.</li>
            <li style="padding-top:10px;text-align:justify">Promouvoir et  appliquer les concepts courants de respect et de protection de l&rsquo;environnement.</li>
            <li style="padding-top:10px;text-align:justify">Produire des  rapports, aux instances de l&rsquo;organisation des activit&eacute;s encadr&eacute;es, relatives  aux observations et aux interventions r&eacute;alis&eacute;es durant l&rsquo;activit&eacute;</li>
          </ul>
          <p align="center" style="font-size:7pt">*  Le masculin est employ&eacute; pour all&eacute;ger le texte, mais repr&eacute;sente autant les deux  sexes.</p>
          <p align="justify"><BR>
          <p align="right"><a href="#top"><img src="../images/fleche_haut.gif" alt="remonter" width="14" height="12" border="0"></a></p>
        </td> </p>
		
	</table></p></div>

						