<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les commanditaires des Sentinelles de la Route</h1>
						
						<div class="textes">
	<p><table border="0" align="center" bordercolor="#0000FF">
      <!--DWLayoutTable-->
      <tr>
        <td align="center"><a href="http://www.saaq.gouv.qc.ca/" target="_blank"><img src="images/logo_saaq.jpg" width="358" height="111" border="0"></a><br><br><br><br>
        <a href="http://www.desjardins.com/fr/votre_caisse/accueil.jsp?transit=81520031" target="_blank"><img src="images/defi_velo_desjardins.gif" width="325" height="153"  border="0"></a><br><br><br>
				<br>
				<br>
        <a href="http://www.tanguay.ca/" target="_blank"><img src="images/Tanguay-Logo.C.jpg" width="300" height="48"border="0"></a><br><br><br><br>
        <!--<a href="http://www.mssig.com/" target="_blank"><img src="images/mssig.jpg" border="0"></a>--></td>
      </tr>
		<tr>
			<td align="center">
				<div align="left">
					<br>
<a href="http://www.mallette.ca/" target="_blank"><font color="red"><strong>Mallette</strong></font></a></span>, 3075, chemin des Quatre-Bourgeois, Bureau 200, Qu&eacute;bec - 418 653-4431<br />
					<strong><font color="red">Option V&eacute;lo</font></strong>, 1415, Frank-Carrel, suite 120, Qu&eacute;bec - 418 681-8356<br>
					
<a href="http://www.sportolympe.com/" target="_blank"><font color="red"><strong>Sport Olympe</strong></font></a>, 441, Boulevard Armand-Paris, Beauport - 418 661-9670</span><br/>
					<span><a href="http://www.c-dupont.ca/index.htm" target="_blank"><font color="red"><strong>Cycles du Pont</strong></font></a>, 136, Route du Pont &agrave; St-Nicolas - 418 831-3457<br>
						<font color="red"><strong>Action v&eacute;lo-service</strong></font>, 2560, Chemin du Fleuve, Saint-Romuald - 418 834-7666<br>
<a href="http://www.cbsf.ca" target="_blank"><font color="red"><strong>Centre du Bicycle Sainte-Foy</strong></font></a>, 3245, chemin Sainte-Foy, Qu&eacute;bec - 418 651-5818<br>
<a href="http://www.apogee-sports.com/index.aspx#/home/" target="_blank"><font color="red"><strong>Apogee</strong></font></a>, 1005, Avenue Saint-Jean-Baptiste, local 139, Qu&eacute;bec - 418 872-6569<br>
						</div>
			</td>
		</tr>
	</table></p>
		
	<p></p>
</div>