<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les commanditaires des Sentinelles de la Route</h1>
						
						<div class="textes">
	<p><table border="0" align="center" bordercolor="#0000FF">
      <!--DWLayoutTable-->
      <tr>
        <td align="center"><a href="http://www.saaq.gouv.qc.ca/" target="_blank"><img src="images/logo_saaq.jpg" width="358" height="111" border="0"></a><br><br><br><br>
        <br><br><br>
				<br>
				<br>
        <a href="http://www.tanguay.ca/" target="_blank"><img src="images/Tanguay-Logo.C.jpg" width="300" height="48"border="0"></a><br><br><br><br>
        <!--<a href="http://www.mssig.com/" target="_blank"><img src="images/mssig.jpg" border="0"></a>--></td>
      </tr>
		<tr>
			<td align="center">
				<div align="left">
					<br>
						<a href="http://www.mallette.ca/" target="_blank"><font color="red"><strong>Mallette</strong></font></a>, 3075, chemin des Quatre-Bourgeois, Bureau 200, Qu&eacute;bec - 418 653-4431<br />
						<a href="http://www.optionvelo.com" target="_blank"><font color="red"><strong>Option V&eacute;lo</strong></font></a>, 1415, Frank-Carrel, suite 120, Qu&eacute;bec - 418 681-8356<br>
						<a href="http://www.sportolympe.com/" target="_blank"><font color="red"><strong>Sport Olympe</strong></font></a>, 441, Boulevard Armand-Paris, Beauport - 418 661-9670</span><br/>
						<a href="http://www.c-dupont.ca/" target="_blank"><font color="red"><strong>Cycles du Pont</strong></font></a>, 136, Route du Pont &agrave; St-Nicolas - 418 831-3457<br>
						<a href="http://www.actionveloservice.com" target="_blank"><font color="red"><strong>Action v&eacute;lo-service</strong></font></a>, 2560, Chemin du Fleuve, Saint-Romuald - 418 834-7666<br>
						<a href="http://www.dynamex.com/courier-quebec-city" target="_blank"><font color="red"><strong>DYNAMEX</strong></font></a>, Québec, 2555 Rue Watt, Québec - 418 652-8330<br>
						<a href="http://www.skidefondcharlesbourg.com" target="_blank"><font color="red"><strong>Club de ski de fond Charlesbourg</strong></font></a>, 375, rue de l'Aventure, Québec -  418 849-9054<br>
						<a href="http://www.lessardbicycles.com" target="_blank"><font color="red"><strong>Lessard Bicycle</strong></font></a>, 909, Pierre-Bertrand, Québec - 418 648-0608<br>
				</div>
			</td>
		</tr>
	</table></p>
		
	<p></p>
</div>