
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les lieux de d&eacute;part des sorties </h1>
						
						<div class="textes">
	<table width="775" border="0" cellspacing="0" cellpadding="3" bgcolor="white">
		<tr height="20">
			<td align="left" valign="bottom" width="275" height="20"><strong>Lieux</strong></td>
			<td align="center" valign="bottom" width="65" height="20"><strong>D&eacute;parts* mardi</strong></td>
			<td align="center" valign="bottom" width="65" height="20"><strong>D&eacute;parts* samedi</strong></td>
			<td valign="bottom" width="275" height="20"><strong>Adresses</strong></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Neufchatel (Carrefour Neufchatel)</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(A)</strong></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(8)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=4605,+boulevard+de+l%E2%80%99Auvergne,+Qu%C3%A9bec,+qc+canada&om=1" target="_blank">4605, boul. de l&rsquo;Auvergne, Neufchatel</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Le Domaine de Maizerets</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(B)</strong></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=1390+d%E2%80%99Estimauville&sll=46.842141,-71.210847&sspn=0.010891,0.019827&gl=ca&ie=UTF8&hq=&hnear=1390+Avenue+d%27Estimauville,+Beauport,+Communaut%C3%A9-Urbaine-de-Qu%C3%A9bec,+Qu%C3%A9bec&ll=46.841759,-71.210182&spn=0.010891,0.019827&t=h&z=16" target="_blank">Entr&eacute;e avenue d&rsquo;Estimauville</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Information touristique (St-Foy)</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(C)</strong></td>
			<td bgcolor="#ffcc33" width="65" height="35"></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&geocode=&q=&near=3300,+avenue+des+H%C3%B4tels,+qu%C3%A9bec+qc+canada&sll=46.752623,-71.289825&sspn=0.010424,0.018711&ie=UTF8&z=15" target="_blank">3300, avenue des H&ocirc;tels, Sainte-Foy</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Beauport (Canac Marquis)</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(D)</strong></td>
			<td bgcolor="#ffcc33" width="65" height="35"></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=420,+Boulevard+Armand-Paris,+Beauport+Qc+Canada&ll=46.883456,-71.185355&spn=0.021178,0.053902&om=1" target="_blank">420, boul. Armand-Paris, Beauport</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Charlesbourg (Jardin Zoologique)</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(E)</strong></td>
			<td bgcolor="#ffcc33" width="65" height="35"></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=9300,+rue+de+la+Faune,+Charlesbourg&om=1" target="_blank">9300, rue de la Faune, Charlesbourg</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Ar&eacute;na Michel Labadie</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"><strong>(F)</strong></td>
			<td bgcolor="#ffcc33" width="65" height="35"></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=4605,+boulevard+de+l%E2%80%99Auvergne,+Qu%C3%A9bec,+qc+canada&om=1" target="_blank">3705, avenue Chauveau</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Rue Plante, St-Nicolas</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(1)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://www.google.ca/search?hl=fr&client=firefox-a&hs=uMa&rls=org.mozilla%3Afr%3Aofficial&q=google+maps+canada&btnG=Rechercher&meta=cr%3DcountryCA&aq=f&aqi=&aql=&oq=&gs_rfai=" target="_blank">Pr&egrave;s de l&rsquo;Intersection de la route du Pont </a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Boulevard des &Eacute;tudiants</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(2)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=160+Boulevard+des+%C3%89tudiants,+Loretteville,+Communaut%C3%A9-Urbaine-de-Qu%C3%A9bec,+Qu%C3%A9bec&sll=46.854439,-71.36575&sspn=0.005444,0.011576&dirflg=r&ttype=dep&date=10%2F05%2F24&time=10:42&noexp=0&noal=0&sort=&ie=UTF8&hq=&hnear=160+Boulevard+des+%C3%89tudiants,+Loretteville,+Communaut%C3%A9-Urbaine-de-Qu%C3%A9bec,+Qu%C3%A9bec+G2A+1N4&t=h&z=16" target="_blank">Pr&egrave;s de l&rsquo;intersection du boul. Valcartier</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Rue du Vallon Ouest</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(3)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.ca/maps?oe=utf-8&rls=org.mozilla:fr:official&client=firefox-a&um=1&ie=UTF-8&q=rock%E2%80%99n+roll+palace&fb=1&gl=ca&hq=rock%E2%80%99n+roll+palace&hnear=Charlesbourg,+QC&cid=0,0,1344513415774413645&ei=srjZS9HbK4z29ATziZhI&sa=X&oi=local_result&ct=image&resnum=4&ved=0CBgQnwIwAw" target="_blank">Autoroute  20 est, sortie Pintendre (Roch&rsquo;n Roll Palace)</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Charny (Caisse pop)</td>
			<td bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(4)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=9009,+boulevard+du+Centre-Hospitalier,+Charny,+Qc+Canada&ll=46.7223,-71.266465&spn=0.021241,0.053902&om=1" target="_blank">9019, boul. du Centre-Hospitalier, Charny </a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Parc industriel St-Augustin </td>
			<td bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(5)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.com/maps?f=l&hl=en&q=&near=200,+route+de+Fossambault,+St-Augustin+qc+canada&om=1" target="_blank">Usine Louis Garneau</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Quai de L&eacute;vis</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(6)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=Resto-Pub+St-Louis+1997+Inc,+L%C3%A9vis,+Qu%C3%A9bec&sll=46.809973,-71.18675&sspn=0.002632,0.005788&dirflg=r&ttype=dep&date=10%2F05%2F24&time=10:49&noexp=0&noal=0&sort=&ie=UTF8&hq=Resto-Pub+St-Louis+1997+Inc,&hnear=L%C3%A9vis,+QC&ll=46.810561,-71.186621&spn=0.005265,0.011576&t=h&z=17" target="_blank">Gare piste cyclable, direction St-Vallier</a></td>
		</tr>
		<tr height="35">
			<td bgcolor="#ffcc33" width="275" height="35">Tour de l&rsquo;&Icirc;le d&rsquo;Orl&eacute;ans</td>
			<td align="center" bgcolor="#01a54f" width="65" height="35"></td>
			<td align="center" bgcolor="#ffcc33" width="65" height="35"><strong>(7)</strong></td>
			<td bgcolor="red" width="275" height="35"><a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=Resto-Pub+St-Louis+1997+Inc,+L%C3%A9vis,+Qu%C3%A9bec&sll=46.809973,-71.18675&sspn=0.002632,0.005788&dirflg=r&ttype=dep&date=10%2F05%2F24&time=10:49&noexp=0&noal=0&sort=&ie=UTF8&hq=Resto-Pub+St-Louis+1997+Inc,&hnear=L%C3%A9vis,+QC&ll=46.874561,-71.097958&spn=0.002629,0.005788&t=h&z=18" target="_blank">Information touristique (&Agrave; l&rsquo;entr&eacute;e de l&rsquo;&Icirc;le)</a></td>
		</tr>
	</table>
	<p>* Les lettres (A) et les chiffres (1) sont Indiqu&eacute;s sur les pdf des parcours, &agrave; t&eacute;l&eacute;charger dans le calendrier des sorties.</p>
	<p></p>
        </td> </p>
</div>