<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Devenez membre des Sentinelles de la Route</h1>
<div class="textes">
	<p>Pour devenir membre des Sentinelles de la Route, veuillez remplir ce formulaire. Un membre du comit&eacute; de recrutement vous contactera d&rsquo;ici quelques jours.</p>
	<div class="textesgras">
		<p>Tous les champs marqu&eacute;s d&rsquo;un * sont obligatoires.</div>
		<form enctype='multipart/form-data' action='process.php' method='post'>
		
		<table width="100%" border=0>
			<tr>
				<td>Pr&eacute;nom:<font color="#ff0000">*</font></td>
				<td><input type=text name="Prenom" size=30 required="true"></td>
			</tr>
			<tr>
				<td>Nom:<font color="#ff0000">*</font></td>
				<td><input type=text name="Nom" size=30></td>
			</tr>
			<tr>
				<td>T&eacute;l&eacute;phone domicile:<font color="#ff0000">*</font></td>
				<td><input type=text name="Telephonedomicile" size=30></td>
			</tr>
			<tr>
				<td>T&eacute;l&eacute;phone bureau:</td>
				<td><input type=text name="Telephonebureau" size=30></td>
			</tr>
			<tr>
				<td>Autre t&eacute;l&eacute;phone:</td>
				<td><input type=text name="Autretelephone" size=30></td>
			</tr>
			<tr>
				<td>Courriel:<font color="#ff0000">*</font></td>
				<td><input type=text name="Courriel" size=30></td>
			</tr>
			<tr>
				<td>Adresse:</td>
				<td><input type=text name="Adresse" size=30></td>
			</tr>
			<tr>
				<td>Ville:</td>
				<td><input type=text name="Ville" size=30></td>
			</tr>
			<tr>
				<td>Code Postal:</td>
				<td><input type=text name="CodePostal" size=30></td>
			</tr>
			<tr>
				<td>Date de naissance:</td>
				<td><select name="Anneenaissance">
						<option value="2000">2000</option>
						<option value="1999">1999</option>
						<option value="1998">1998</option>
						<option value="1997">1997</option>
						<option value="1996">1996</option>
						<option value="1995">1995</option>
						<option value="1994">1994</option>
						<option value="1993">1993</option>
						<option value="1992">1992</option>
						<option value="1991">1991</option>
						<option value="1990">1990</option>
						<option value="1989">1989</option>
						<option value="1988">1988</option>
						<option value="1987">1987</option>
						<option value="1986">1986</option>
						<option value="1985">1985</option>
						<option value="1984">1984</option>
						<option value="1983">1983</option>
						<option value="1982">1982</option>
						<option value="1981">1981</option>
						<option value="1980">1980</option>
						<option value="1979">1979</option>
						<option value="1978">1978</option>
						<option value="1977">1977</option>
						<option value="1976">1976</option>
						<option value="1975">1975</option>
						<option value="1974">1974</option>
						<option value="1973">1973</option>
						<option value="1972">1972</option>
						<option value="1971">1971</option>
						<option value="1970">1970</option>
						<option value="1969">1969</option>
						<option value="1968">1968</option>
						<option value="1967">1967</option>
						<option value="1966">1966</option>
						<option value="1965">1965</option>
						<option value="1964">1964</option>
						<option value="1963">1963</option>
						<option value="1962">1962</option>
						<option value="1961">1961</option>
						<option value="1960">1960</option>
						<option value="1959">1959</option>
						<option value="1958">1958</option>
						<option value="1957">1957</option>
						<option value="1956">1956</option>
						<option value="1955">1955</option>
						<option value="1954">1954</option>
						<option value="1953">1953</option>
						<option value="1952">1952</option>
						<option value="1951">1951</option>
						<option value="1950">1950</option>
						<option value="1949">1949</option>
						<option value="1948">1948</option>
						<option value="1947">1947</option>
						<option value="1946">1946</option>
						<option value="1945">1945</option>
						<option value="1944">1944</option>
						<option value="1943">1943</option>
						<option value="1942">1942</option>
						<option value="1941">1941</option>
						<option value="1940">1940</option>
						<option value="1939">1939</option>
						<option value="1938">1938</option>
						<option value="1937">1937</option>
						<option value="1936">1936</option>
						<option value="1935">1935</option>
						<option value="1934">1934</option>
						<option value="1933">1933</option>
						<option value="1932">1932</option>
						<option value="1931">1931</option>
						<option value="1930">1930</option>
						<option value="1929">1929</option>
						<option value="1928">1928</option>
						<option value="1927">1927</option>
						<option value="1926">1926</option>
						<option value="1925">1925</option>
						<option value="1924">1924</option>
						<option value="1923">1923</option>
						<option value="1922">1922</option>
						<option value="1921">1921</option>
						<option value="1920">1920</option>
					</select>
					<select name="Moisnaissance">
						<option value="01">Janvier</option>
						<option value="02">F&eacute;vrier</option>
						<option value="03">Mars</option>
						<option value="04">Avril</option>
						<option value="05">Mai</option>
						<option value="06">Juin</option>
						<option value="07">Juillet</option>
						<option value="08">Août</option>
						<option value="09">Septembre</option>
						<option value="10">Octobre</option>
						<option value="11">Novembre</option>
						<option value="12">D&eacute;cembre</option>
					</select>
					<select name="Journaissance">
						<option value="01">01</option>
						<option value="02">02</option>
						<option value="03">03</option>
						<option value="04">04</option>
						<option value="05">05</option>
						<option value="06">06</option>
						<option value="07">07</option>
						<option value="08">08</option>
						<option value="09">09</option>
						<option value="10">10</option>
						<option value="11">11</option>
						<option value="12">12</option>
						<option value="13">13</option>
						<option value="14">14</option>
						<option value="15">15</option>
						<option value="16">16</option>
						<option value="17">17</option>
						<option value="18">18</option>
						<option value="19">19</option>
						<option value="20">20</option>
						<option value="21">21</option>
						<option value="22">22</option>
						<option value="23">23</option>
						<option value="24">24</option>
						<option value="25">25</option>
						<option value="26">26</option>
						<option value="27">27</option>
						<option value="28">28</option>
						<option value="29">29</option>
						<option value="30">30</option>
						<option value="31">31</option>
					</select></td>
			</tr>
			<tr>
				<td>Taille du maillot:</td>
				<td><select name="maillot">
						<option value="XSmall">X-Small (Femme)</option>
						<option value="Petit(femme)">Petit (Femme)</option>
						<option value="Petit(homme)">Petit (Homme)</option>
						<option value="Medium(femme)">M&eacute;dium (Femme)</option>
						<option value="Medium(homme)">M&eacute;dium (Homme)</option>
						<option value="Large(femme)">Large (Femme)</option>
						<option value="Large(homme)">Large (Homme)</option>
						<option value="XLarge(femme)">X-Large (Femme)</option>
						<option value="XLarge(homme)">X-Large (Homme)</option>
						<option value="2XLarge(homme)">2X-Large (Homme)</option>
						<option value="3XLarge(homme)">3X-Large (Homme) </option>
					</select></td>
			</tr>
			<tr>
				<td>Groupe de vitesse:</td>
				<td><select name="Groupedevitesse">
						<option value="18">18 km/h</option>
						<option value="20">20 km/h</option>
						<option value="22">22 km/h</option>
						<option value="25">25 km/h</option>
						<option value="28">28 km/h</option>
						<option value="30">30 km/h</option>
						<option value="32">32 km/h</option>
						<option value="35">35 km/h </option>
					</select></td>
			</tr>
			<tr>
				<td>No ass maladie:</td>
				<td><input type=text name="Noassmaladie" size=30></td>
			</tr>
			<tr>
				<td>Personne &agrave; contacter en cas d'urgence:</td>
				<td><input type=text name="Personneurgence" size=30></td>
			</tr>
			<tr>
				<td>Lien de parent&eacute; du contact en cas d'urgence:</td>
				<td><select name="Lien">
						<option value="Conjoint(e)">Conjoint(e)</option>
						<option value="Pere">Pere</option>
						<option value="Mere">Mere</option>
						<option value="Frere">Frere</option>
						<option value="Soeur">Soeur</option>
						<option value="Ami(e)">Ami(e)</option>
						<option value="Autre">Autre </option>
					</select></td>
			</tr>
			<tr>
				<td>T&eacute;l&eacute;phone domicile du contact en cas d'urgence:</td>
				<td><input type=text name="Telephonedomicilepersonne" size=30></td>
			</tr>
			<tr>
				<td>T&eacute;l&eacute;phone bureau du contact en cas d'urgence:</td>
				<td><input type=text name="Telephonebureaupersonne" size=30></td>
			</tr>
			<tr>
				<td>Autre t&eacute;l&eacute;phone du contact en cas d'urgence:</td>
				<td><input type=text name="Telephoneautrepersonne" size=30></td>
			</tr>
			<tr>
				<td>Recrut&eacute; par:</td>
				<td><input type=text name="Recrutepar" size=30></td>
			</tr>
		</table>
		<input type="submit" value="Envoyer"> <input type=reset value="Effacer">
		
	</div>