
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES ENCADREMENTS DE LA SAISON 2010</h1><br>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrements.php">MAI </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsjuin.php">JUIN</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsjuillet.php">JUILLET</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsseptembre.php">SEPTEMBRE</a></font></td>
			</tr>
		</table> 
						
						<div class="textes">
							<p>Vous devez nous informer de votre présence ou de votre absence dans la semaine précédant chaque encadrement, sur le lien de l&rsquo;inscription de l&rsquo;événement dans le calendrier.<br>
			<br>

			<body bgcolor="#FFCC33">

<!-- Start Calendar, ao?t 2010 -->
<p align="center"><font color="#ed1b24" size="5" face="Arial">Encadrements de AO&Ucirc;T 2010</font></p>
<table width="100%" border="1" cellspacing="0" bordercolor="#000000" cellpadding="4">
  <tr>
				<td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
				<td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
				<td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">1<br>
						&nbsp;<br>
						&nbsp;<br>
						&nbsp;<br>
						&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">2<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">3<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">4<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">5<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ffffcc" align="left"><font color="#000000" size="3" face="Arial">6<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
				<td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>8</strong><br>
					</font><a href="encadrements/suicide.php">Randonn&eacute;e pour la pr&eacute;vention du Suicide</a><font color="#000000" size="3" face="Arial">&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">11<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">12<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">13<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>14</strong><br>
					</font><a href="encadrements/lorettain.php">Festival Lorettain</a>
					
					<p><font color="#000000" size="3" face="Arial">&nbsp;</font></p>
				</td>
  </tr><tr>
				<td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>15</strong><br>
					</font><a href="encadrements/defiQuebec.php">Cyclo-D&eacute;fi de Qu&eacute;bec</a><font color="#000000" size="3" face="Arial">&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">17<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">18<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">19<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font size="3" color="#000000" face="Arial">20<br></font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>21</strong><br>
					</font><a href="encadrements/vireevelo.php">Grande Vir&eacute;e-V&eacute;lo de l'AICQ</a></td>
  </tr><tr>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">22</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">23<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
				<td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">24<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">25<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">26<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">27<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>28</strong><br>
						<a href="encadrements/raid.php">Raid V&eacute;lo Mag</a></font><font color="#000000" size="3" face="Arial">&nbsp;&nbsp;</font></td>
  </tr><tr>
				<td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>29</strong><br>
					</font><a href="encadrements/marathon.php">Marathon des Deux-Rives</a><font color="#000000" size="3" face="Arial">&nbsp;</font></td>
				<td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><b>30</b><br>
					</font><a href="encadrements/CrossCountry.php">Championnat du monde au Mont St-Anne</a></td>
				<td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><b>31</b><br>
					</font><a href="encadrements/CrossCountry.php">Championnat du monde</a><font color="#000000" size="3" face="Arial">&nbsp;</font><a href="encadrements/CrossCountry.php">au Mont St-Anne</a></td>
    <td valign="top" colspan="4"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
  </tr>
</table>
<!-- End Calendar, ao?t 2010 -->

</body>
</html>
	</p>
		</div>