<link href="../style.css" rel="stylesheet" media="screen">
<h1>LES ENCADREMENTS DE LA SAISON 2011</h1><br>

<div class="textes">
	<p>Nous travaillons pr&eacute;sentement sur le nouveau site des Sentinelles. Le calendrier des &eacute;v&egrave;nements n'est pas encore compl&eacute;t&eacute;, mais voici un aper&ccedil;u des &eacute;v&egrave;nements pour la saison 2011 :<br />
	
<table width="550"><tbody>
<tr><td colspan=2 style="font-size: 14px;">Mai</td></tr>
<tr><td style="width: 150px;">Dimanche 1 mai</td><td>Demi-marathon Inernational de Qu&eacute;</td></tr>
<tr><td>14-15 mai</td><td>Formation premiers soins</td></tr>
<tr><td>Mercredi 18 mai</td><td>Randonn&eacute;e du Silence</td></tr>
<tr><td>Samedi 28 mai</td><td>Raid fondation H&ocirc;tel-Dieu de L&eacute;vis</td></tr>
<tr><td>Dimanche 29 mai</td><td>Randonn&eacute;e M&eacute;moire Rona</td></tr>
<tr><td colspan=2><br /></td></tr>
<tr><td colspan=2 style="font-size: 14px; font-weight: bold;">Juin</td></tr>
<tr><td>4-5 juin</td><td>Formation premiers soins</td></tr>
<tr><td>Dimanche 5 juin</td><td>Descente Royale</td></tr>
<tr><td>Dimanche 5 juin</td><td>Tour de l'&Icirc;le d'Orl&eacute;an</td></tr>
<tr><td>Dimanche 12 juin</td><td>La 5 de Beauport</td></tr>
<tr><td>Vendredi 17 juin</td><td>Triatlhon &Eacute;cole des Pionniers</td></tr>
<tr><td>Samedi 18 juin</td><td>Tour de Beauce</td></tr>
<tr><td>Dimanche 19 juin</td><td>Randonn&eacute;e Tanguay</td></tr>
<tr><td>18-19 juin</td><td>V&eacute;lirium Mont-St-Anne</td></tr>
<tr><td>Samedi 25 juin</td><td>V&eacute;lirium Raid V&eacute;lo Mag</td></tr>
<tr><td colspan=2><br /></td></tr>
<tr><td colspan=2 style="font-size: 14px; font-weight: bold;">Juillet</td></tr>
<tr><td>2 juillet</td><td>D&eacute;fi V&eacute;lo Andr&eacute; C&ocirc;t&eacute;</td></tr>
<tr><td>2-3 juillet</td><td>V&eacute;lirium Mont-St-Anne</td></tr>
<tr><td>8-9-10 juillet</td><td>D&eacute;fi contre le cancer</td></tr>
<tr><td colspan=2><br /></td></tr>
<tr><td colspan=2 style="font-size: 14px; font-weight: bold;">Ao&ucirc;t</td></tr>
<tr><td>Samedi 13 ao&ucirc;t</td><td>Festival Lorettain</td></tr>
<tr><td>Dimanche 21 ao&ucirc;t</td><td>Cyclo-D&eacute;fi de Qu&eacute;bec</td></tr>
<tr><td>Dimanche 28 ao&ucirc;t</td><td>Marathon des Deux-Rives</td></tr>
<tr><td colspan=2><br /></td></tr>
<tr><td colspan=2 style="font-size: 14px; font-weight: bold;">Septembre</td></tr>
<tr><td>Samedi 10 septembre</td><td>D&eacute;lo V&eacute;lo Desjardins</td></tr>
<tr><td>Samedi 17 septembre</td><td>Manifestation &laquo;Faites nous de la place&raquo;</td></tr>
<tr><td>Dimanche 18 septembre</td><td>Randonn&eacute;e Lotbini&egrave;re</td></tr>
</tbody></table>

 <br>
		<a href="encadrements2010.php"><font color="#FF0000">Cliquez ici</font></a> pour voir le calendrier de 2010.
		<br>
  	</p>
</div>