
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES ENCADREMENTS DE LA SAISON 2010</h1><br>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsjuin.php">JUIN </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsjuillet.php">JUILLET</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsaout.php">AO&Ucirc;T</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="encadrementsseptembre.php">SEPTEMBRE</a></font></td>
			</tr>
		</table> 
						
						<div class="textes">
							<p>Vous devez nous informer de votre présence ou de votre absence dans la semaine précédant chaque encadrement, sur le lien de l&rsquo;inscription de l&rsquo;événement dans le calendrier.<br>
			<br>

			<body bgcolor="#FFCC33">

<!-- Start Calendar, mai 2010 -->
<p align="center"><font size="5" color="#ed1b24" face="Arial">Encadrements de MAI 2010</font></p>
<table width="100%" border="1" cellspacing="0" bordercolor="#FFCC33" cellpadding="4">
  <tr>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
    <td valign="top" colspan="6"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">1<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><b>2</b><br>
						<a href="http://www.marathonquebec.com/sites/demi-html/generales.html" target="_blank"><b>Demi-Marathon de Qu&eacute;bec<br>
								<img src="images/logo_demi_marathon.gif" alt="" width="99" height="77" border="0"></b></a></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">3<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">4<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">5<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">6<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font size="3" color="#000000" face="Arial"><b>8</b><br>
						<a href="encadrements/formationEncadreur.php"><b>Formation d'encadreur</b></a>
            <br><br><a href="javascript:void window.open('http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=3705,+Chauveau,+Qc&sll=46.834556,-71.345161&sspn=0.010936,0.01929&ie=UTF8&hq=&hnear=3705+Avenue+Chauveau,+Qu%C3%A9bec,+Communaut%C3%A9-Urbaine-de-Qu%C3%A9bec,+Qu%C3%A9bec+G2C+1A3&ll=46.832115,-71.346395&spn=0.005468,0.013733&t=h&z=17','popup','Width=780,height=580,scrollbars=1,resizable=1,')">Endroit et trajet pour s&rsquo;y rendre</a></font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">11<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">12<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">13<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">14<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">15<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">17<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">18<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><b>19</b><br>
					</font><a href="encadrements/silence.php">INSCRIPTION</a><font color="#000000" size="3" face="Arial"><a href="encadrements/silence.php"><b><br>
								Tour du silence </b></a></font>
					<p><font color="#000000" size="3" face="Arial"><a href="http://www.fqsc.net/cyclosportif/tour-du-silence-edition-2010" target="_blank">Renseignements additionnels</a> </font></p>
				</td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">20<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">21<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">22<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>23<br>
						</strong></font><a href="encadrements/festivelomec.php">INSCRIPTION</a>
					<p><font color="#000000" size="3" face="Arial"><a href="javascript:void window.open('http://www.mec.ca/Main/content_text.jsp?FOLDER%3C%3Efolder_id=2534374302888241&bmUID=1273691651929&bmLocale=fr_CA','popup','Width=1024,height=768,scrollbars=1,resizable=1,')"<strong>Festiv&eacute;lo MEC, </strong>une activit&eacute; pour faire conna&icirc;tre le club</a><a href="http://www.mec.ca/Main/content_text.jsp?FOLDER%3C%3Efolder_id=2534374302887013&languageToggle=fr_CA&bmForm=setLanguageCookie&bmFormID=1272010005612&bmSubmit=SetLanguageCookie&bmHash=e11458871b3277431043e2ed602e2494695cbbcf" target="_blank">&nbsp;</a></font></p>
				</td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">24<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">25<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">26<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">27<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">28<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">29<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><b>30</b><br>
					</font><a href="encadrements/memoire.php">INSCRIPTION</a><font color="#000000" size="3" face="Arial"><a href="encadrements/memoire.php"><b><br>
								Marche de la m&eacute;moire RONA</b></a><br>
						<br>
						<a href="http://www.lamarchedelamemoire.com/quebec-renseignements" target="_blank">Renseignements additionnels</a> </font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">31<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" colspan="5"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
  </tr>
</table>
<!-- End Calendar, mai 2010 -->

</body>
</html>
	</p>
		</div>