
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>L&rsquo;historique des <b style="color:red">Sentinelles</b> de la Route</b></h1>
						
						<div class="textes">
		<p>Le club d&#8217;encadreurs cyclistes <b>Les</b> <b style="color:red">Sentinelles</b> de la <b>Route</b> fut fond&eacute; selon la partie 3 de la loi
          des compagnies du Qu&eacute;bec, en mars 1998. Ses fondateurs sont Beno&icirc;t
          Miller, R&eacute;jean O'Connor et Patrick Robitaille. Chaque ann&eacute;e,
          les organisateurs de randonn&eacute;es cyclistes de la grande
          r&eacute;gion de Qu&eacute;bec peuvent compter sur un service d&#8217;encadrement
          professionnel pour voir au bon d&eacute;roulement de leurs pr&eacute;cieux
          &eacute;v&eacute;nements.</p>
        <p align="justify"> Annuellement, pr&egrave;s d&#8217;une vingtaine d&#8217;organisations,
          regroupant plus de 10 000 participants, b&eacute;n&eacute;ficient de l&#8217;&eacute;troite
          collaboration des <b style="color:red">Sentinelles</b> de la <b>Route</b> pour
          s&#8217;assurer que la s&eacute;curit&eacute; sera au c&#339;ur de leurs r&eacute;alisations.
          Le succ&egrave;s du Club repose sur l&#8217;engagement b&eacute;n&eacute;vole
          de nos membres qui sont avant tout des passionn&eacute;s du v&eacute;lo et
          de la s&eacute;curit&eacute;. </p>
	<table width="100%" border="0" cellspacing="2" cellpadding="0">
		<tr>
			<td>
				<div class="textesgras">
					<p><span class="textesgras">Photo souvenir : Premier &quot;D&eacute;fi des Sentinelles&quot; en </span>19<span class="textesgras">98</span></p>
				</div>
			</td>
			<td></td>
		</tr>
		<tr>
			<td align="center" colspan=2><img src="images/BENOIT.jpg" width="510" height="491"></td>
		</tr>
		<tr>
			<td align="center" colspan=2>
				<div class="textesphotosHisto">
					<p>Dans l'ordre habituel : (rang&eacute;e avant) Isabelle Plante*, Jean-Marie Gigu&egrave;re* et Gaston Leblanc, (rang&eacute;e du centre) Jean Furois et Gaby Talbot, (rang&eacute;e arri&egrave;re) Jacques Cloutier, Philippe Gingras, Beno&icirc;t Miller, Jean-Marie Gagnon* et Bruno Lapointe</p>
					<p>* b&eacute;n&eacute;voles lors de ce d&eacute;fi</p>
				</div>
			</td>
		</tr>
		<tr>
			<td height="50"></td>
			<td></td>
		</tr>
		<tr>
			<td align="center"><span class="textesgras">Logo des Sentinelles de la Route de 1998 &agrave; 2004</span></td>
			<td align="center"><span class="textesgras">Logo des Sentinelles de la Route en 2004</span></td>
		</tr>
		<tr>
			<td align="center"><img src="images/sentinelles_1998_2004.jpg" width="314" height="198"></td>
			<td align="center"><img src="images/sentinelles_2004s.jpg" width="262" height="247" border="0"></td>
		</tr>
		<tr>
			<td height=20></td>
			<td></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><span class="textesgras">Logo des Sentinelles de la Route en 2010</span></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><img src="images/logo_sentinelles_2010.jpg" alt="" width="274" height="255" border="0"></td>
		</tr>
	</table>
	<p align="right"><a href="#top"><img src="../images/fleche_haut.gif" alt="remonter" width="14" height="12" border="0"></a></p>
        </td> </p>
</div>