
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les membres des <b style="color:red">Sentinelles</b> de la  <b>Route</b></h1>
						
						<div class="textes">
	<p>Le Club compte actuellement au-del&agrave; de cent (100) membres r&eacute;guliers auxquels se joignent d&rsquo;autres cyclistes d&rsquo;exp&eacute;rience lors d&rsquo;&eacute;v&eacute;nements de grande envergure. Nos membres b&eacute;n&eacute;voles sont tous des personnes responsables engag&eacute;s dans une cause en lien avec une passion commune, celle du v&eacute;lo.
		 Ils s&rsquo;engagent &agrave; respecter les r&egrave;glements du Club et &agrave; adopter un comportement exemplaire en mati&egrave;re de s&eacute;curit&eacute; et de courtoisie lorsqu&rsquo;ils portent les couleurs des <b style="color:red">Sentinelles</b> de la <b>Route</b>.</p>
	<table width="19" border="0" cellspacing="2" cellpadding="0">
		<tr>
			<td><img src="images/groupe_cancer2009.jpg" alt="" width="797" height="459" border="0"></td>
		</tr>
		<tr>
			<td>
				<div class="textesphotos">
					<font color="#FF0000">Les Sentinelles de la Route</font> - 11 juillet 2009 - Cyclo-d&eacute;fi contre le cancer </div>
			</td>
		</tr>
		<tr>
			<td height="40"></td>
		</tr>
		<tr>
			<td align="center"><img src="images/sentinelles_2008.jpg"></td>
		</tr>
		<tr>
			<td align="center">
				<div class="textesphotosHisto">
					<font color="#FF0000">Les Sentinelles de la Route</font> - 8 juin 2008 - Randonn&eacute;e
        de la Fondation Maurice Tanguay </div>
			</td>
		</tr>
		<tr>
			<td height="40"></td>
		</tr>
		<tr>
			<td align="center"><img src="images/pic1.jpg" width="565" height="424"></td>
		</tr>
		<tr>
			<td align="center">
				<div class="textesphotosHisto">
					<font color="#FF0000">Les Sentinelles de la Route</font> - 12 juin 2005 - Randonn&eacute;e
        de la Fondation Maurice Tanguay </div>
			</td>
		</tr>
	</table>
	<p></p>
	<p align="right"><a href="#top"><img src="../images/fleche_haut.gif" alt="remonter" width="14" height="12" border="0"></a></p>
        </td> </p>
</div>