
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Liens utiles</h1>
						
					<div class="textes">
							<p><p align="left" class="style1"><strong>Nos Commanditaires</strong></p>
	<a href="http://www.saaq.gouv.qc.ca" target="_blank"><font color="red">Société de l'Assurance Automobile du Québec</font></a>
	<p><a href="http://www.desjardins.com/fr/votre_caisse/accueil.jsp?transit=81520031" target="_blank"><font color="red">Caisse populaire Desjardins de Québec</font></a> </p>
	<p><a href="http://www.tanguay.ca/" target="_blank"><font color="red">Ameublement Tanguay</font></a></p>
	<p align="left" class="style1"><strong>Nos  donateurs </strong></p>
	<a href="http://www.bicyclesrecord.com" target="_blank"><font color="red">Bicycles Record</font></a>
	<p><a href="http://www.cbsf.ca/accueil.php" target="_blank"><font color="red">Centre du Bicycle Sainte-Foy</font></a></p>
	<p><a href="http://www.saint-antoine.com/menu.html" target="_blank"><font color="red">Restaurant le Panache</font></a></p>
	<p><a href="http://www.lecharlemagne.qc.ca" target="_blank"><font color="red">Boutique le Charlemagne</font></a></p>
	<p align="left" class="style1"><strong>Autres clubs de la région</strong></p>
	<a href="http://www.cyclorizon.qc.ca" target="_blank"><font color="red">Club cycliste Cyclorizon</font></a>
	<p><a href="http://www.sportentete.qc.ca" target="_blank"><font color="red">Club cycliste Sport-en-Tête</font></a></p>
	<p><a href="http://www.clubcyclo-kebek.com/" target="_blank"><font color="red">Club Cyclo-K&eacute;b&egrave;k</font></a></p>
	<p align="left" class="style1"><strong>Autres Liens</strong></p>
	<a href="http://www.communicationrectoverso.ca/"  target="_blank"><font color="red">Communications Graphique Recto-Verso</font></a> (documents ptomotionnels et conception du site Web des Sentinelles de la Route, mai 2010)<p><a href="http://www.everyoneweb.fr/cadas2000/"  target="_blank"><font color="red">CADAS,c'est &ccedil;a...des amis</font></a></p>
	<p><a href="http://www.promo-velo.org"  target="_blank"><font color="red">Promo-V&eacute;lo</font></a> (promotion du v&eacute;lo)</p>
	<p><a href="http://www.velo.qc.ca" target="_blank"><font color="red">V&eacute;lo Qu&eacute;bec</font></a> (formation d'encadreur cycliste)</p>
	<p><a href="http://www.letour.fr/" target="_blank"><font color="red">Le Tour de France</font></a> (site officiel du Tour)</p>
  <p><a href="http://www.velocia.ca/" target="_blank"><font color="red">Velocia</font></a> (site pour amateurs de v&eacute;los)</p>
</div>