<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Pour nous joindre</h1>
						
						<div class="textes">
							<p>N&rsquo;h&eacute;sitez-pas de communiquer avec les <b style="color:red">SENTINELLES</b> DE LA <b style="color:black">ROUTE</b>.<br>C&rsquo;est avec plaisir que nous r&eacute;pondrons rapidement &agrave; votre demande.<br>
	</p>
	</div>
					<form action="merci.php" method="post" name="Rejoindre">
	<table width="443" border="0" cellspacing="4" cellpadding="2">
		<tr align="center" bgcolor="#FF0000">
			<td align="left" valign="middle" bgcolor="#FF0000">
				<div align="left">
					<font size="1" color="white" face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular">NOM </font></div>
			</td>
			<td>
				<div align="left">
					<font color="#FF0000"><input type="text" name="nom" size="48" tabindex="1"></font></div>
			</td>
		</tr>
		<tr>
			<td valign="top" bgcolor="#FF0000"><font size="1" color="white" face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular">COURRIEL</font></td>
			<td bgcolor="#FF0000">
				<div align="left">
					<font color="#FF0000"><input type="text" name="courriel" size="48" tabindex="3"></font></div>
			</td>
		</tr>
		<tr>
			<td valign="top" bgcolor="#FF0000"><font size="1" color="white" face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular">T&Eacute;L&Eacute;PHONE</font></td>
			<td bgcolor="#FF0000">
				<div align="left">
					<font color="#FF0000"><input type="text" name="telephone" size="48" tabindex="4"></font></div>
			</td>
		</tr>
		<tr>
			<td valign="top" bgcolor="#FF0000"><font size="1" color="white" face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular">DEMANDE</font><b></b></td>
			<td>
				<div align="left">
					<font color="#FF0000"><textarea name="message" rows="5" cols="45" tabindex="5"></textarea></font></div>
			</td>
		</tr>
		<tr>
			<td bgcolor="white"></td>
			<td bgcolor="white"><font color="#FF0000"><input type="submit" name="submitButtonName" value="Envoyer"></font></td>
		</tr>
	</table>
	<div class="textes">
		<p>
				Les Sentinelles de la Route<br>
				C.P. 9802, Succ. postale Ste-Foy<br>
			Qu&eacute;bec (Qu&eacute;bec)<br>
				G1V 4C3</p>
		<div class="textesgras"><br>
			
			<p style="font-size:12pt">Le CONSEIL D&rsquo;ADMINISTRATION de 2011-2012</p>
		</div>
		<table width="100%" border="0" cellspacing="2" cellpadding="0">
			<tr>
			   <td align="center" width="841">
					<table border=0 width="433" align="left">
			     <tr height="67">
			        <td class="textesCellule" align="center" width="137" height="67">
                <img src="images/ca/yb.jpg"><br>
                Pr&eacute;sident<br>
				        <a href="mailto:breton.yvon@videotron.ca"><font color="red">Yvon Breton</font></a>
              </td>
              <td width="10" height="67"></td>
              <td class="textesCellule" align="center" width="125" height="67">
                <img src="images/ca/gbordeleau.jpg"><br>
								Vice-pr&eacute;sident<br>
								<a href="mailto:lessentinelles@hotmail.com"><font color="red">Guy Bordeleau</font></a></td>
              <td width="10" height="67"></td>
              <td class="textesCellule" align="center" width="140" height="67">
                <img src="images/ca/jb.jpg"><br>
                Secr&eacute;taire <br>
				        <a href="mailto:jonathan.breton@gmail.com"><font color="red">Jonathan Breton</font></a></td>
							<td class="textesCellule" align="center" width="11" height="67"></td>
						</tr>
			     </table>
					<table align="left" border=0>
						<tr>
							<td class="textesCellule" align="center"><img src="images/ca/hj.jpg"><br>
									Directeur Finances<br>
								<a href="mailto:henri.jalbert@mallette.ca"><font color="red">Henri Jalbert</font></a></td>
						</tr>
					</table>
				</td>			 	
			 </tr>
			 <tr>
			   <td align="center" width="841">
			      <table align="left" border=0>
			      <tr>
							<td width="10"></td>
							<td class="textesCellule" align="center">
                <img src="images/ca/rc.jpg"><br>
                Directeur<br>Marketing<br>
								<a href="mailto:rectoverso@videotron.qc.ca"><font color="red">R&eacute;jean Cloutier</font></a></td>
              <td width="10"></td>
              <td class="textesCellule" align="center"><img src="images/ca/rogerfortin.jpg"><br>
								Directeur<br>Encadrements<br>
								<a href="mailto:lessentinelles@hotmail.com"><font color="red">Roger Fortin</font></a></td>
				      <td width="10"></td>
              <td class="textesCellule" align="center">
                <img src="images/ca/ab.jpg"><br>
                Directrice<br>&Eacute;quipement <br>
								<a href="mailto:anne.boudreau@videotron.ca"><font color="red">Anne Boudreau</font></a></td>
				      <td width="10"></td>
              <td class="textesCellule" align="center">
                <img src="images/ca/guillaumetalbot.jpg"><br>
                Directeur<br>
								Recrutement<br>
			          <a href="mailto:lessentinelles@hotmail.com"><font color="red">Guillaume Talbot</font></a></td>
				      <td width="10"></td>
              <td class="textesCellule" align="center">
                <img src="images/ca/yvesb.jpg"><br>
                Directeur<br>Sorties <br>
								<a href="mailto:yves.beaudoin5@videotron.ca"><font color="red">Yves Beaudoin</font></a></td>
			      </tr>
			      </table>
			      
			   </td>
			  </tr>
		  </table>
		<p>  </p>
	</div>

