
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les r&eacute;alisations des Sentinelles de la Route</h1>
						
						<div class="textes">
		<p>
	<table width="750" border="0" cellspacing="2" cellpadding="2">
		<tr align="left" valign="middle">
			<td class="textes" bgcolor="#ed1b24" width="325"><strong><font color="white">&Eacute;v&eacute;nements</font></strong></td>
			<td class="textes" bgcolor="#ed1b24" width="400"><strong><font color="white">Oeuvres de bienfaisance</font></strong></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="red">Le Cyclo-d&eacute;fi contre le cancer</font></td>
			<td class="textes" width="400">L&rsquo;H&ocirc;pital G&eacute;n&eacute;ral juif</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e Tanguay - Tour de la Capitale </font></td>
			<td class="textes" width="400">Fondation Maurice-Tanguay, Enfants malades</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e Louis-Garneau</font></td>
			<td class="textes" width="400">Fondation Louis-Garneau</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">D&eacute;fi Sant&eacute;</font></td>
			<td class="textes" width="400">Fondation Robert-Giffard</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Randonn&eacute;e La Cinq de Beauport </font></td>
			<td class="textes" width="400">Fonds d'&eacute;lite sportive Normand-Brunet</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e cycliste de Sainte-Claire</font></td>
			<td class="textes" width="400">Sports amateurs locaux</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e en coeur</font></td>
			<td class="textes" width="400">Fondation H&ocirc;pital Laval - Pavillon de pr&eacute;vention des maladies cardiaques</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e des gouverneurs</font></td>
			<td class="textes" width="400">Fondation des gouverneurs - Sport amateur</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Tour de l'&Icirc;le d'Orl&eacute;ans</font></td>
			<td class="textes" width="400">Fondation des sourds</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e de Frampton</font></td>
			<td class="textes" width="400">Pr&eacute;vention du suicide - pour les organismes SERI et La Barre du jour</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e des deux (2) Rives</font></td>
			<td class="textes" width="400">Crutec - pour le transport en commun</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e v&eacute;lo-c&eacute;leste</font></td>
			<td class="textes" width="400">Ville de Qu&eacute;bec - pour les jeunes</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La Randonn&eacute;e V&eacute;lo Trans-Qu&eacute;bec</font></td>
			<td class="textes" width="400">F&eacute;d&eacute;ration qu&eacute;b&eacute;&ccedil;oise des centres communautaires de loisir</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Travers&eacute;e du Canada</font></td>
			<td class="textes" width="400">Guy Bolduc, journaliste, pour l'autisme</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Club optimiste de Saint-Augustin</font></td>
			<td class="textes" width="400">Club optimiste Saint-Augustin</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Randonn&eacute;e du coeur de Saint-&Eacute;douard de Lotbini&egrave;re</font></td>
			<td class="textes" width="400">Comit&eacute; du coeur - CLSC Centre de sant&eacute; Arthur-Caux</td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Le Tour du Lac Saint-Jean</font></td>
			<td class="textes" width="400"><font color="black">Centre de solidarit&eacute; internationale - pour le Burkina Faso</font></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La V&eacute;lo-F&ecirc;te des enfants</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Le Marathon des deux (2) rives</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Le Triathlon de L&eacute;vis</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">V&eacute;l&eacute;rium - La coupe du monde
        du v&eacute;lo de montagne</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Marathon Qu&eacute;bec-Montmorency<br>
					(Portion sur route - comp&eacute;tition de v&eacute;lo de montagne)</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La course Transcanadienne</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">La course Condo Val-des-Neiges</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Le Grand Prix cycliste de Portneuf</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Le Grand Prix cycliste de Beauce</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">D&eacute;fi des Sentinelles</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Les fous du v&eacute;lo</font></td>
			<td class="textes" width="400"></td>
		</tr>
		<tr>
			<td class="textes" width="325"><font color="#FF0000">Les 3 Jours Hull-Qu&eacute;bec</font></td>
			<td class="textes" width="400"></td>
		</tr>
	</table>
	<p align="left"></p>
	<p align="left"></p>
	<p align="left"></p>
      <p align="left"></p>
      <p align="left"></p>
      <p align="left"></p>
      <p align="left"></p>
    
          
       
          <p align="right"><a href="#top"><img src="../images/fleche_haut.gif" alt="remonter" width="14" height="12" border="0"></a></p>
        </td> </p>
</div>