
<link href="../style.css" rel="stylesheet" media="screen">
<h1>Les r&egrave;glements des Sentinelles de la Route</h1>
<div class="textes">
	<p>
		<li><a href="#Intro"><font color="red">Introduction</font></a>
		<li><a href="#Reglement"><font color="red">R&egrave;glements des membres</font></a>
		<li><a href="#ConsEnc"><font color="red">Consignes de s&eacute;curit&eacute; lors des encadrements</font></a>
		<li><a href="#Technique"><font color="red">Techniques d&rsquo;encadrements</font></a>
		<li><a href="#ConsSortie"><font color="red">Consignes de s&eacute;curit&eacute; lors des sorties</font></a><br>
		<br>
		
			Les r&egrave;glements, consignes et techniques suivantes sont en place afin d&rsquo;assurer la s&eacute;curit&eacute; des membres et le bon d&eacute;roulement des op&eacute;rations du Club.&nbsp; De plus, ils visent &agrave; donner une bonne image bas&eacute;e sur le professionnalisme qui caract&eacute;rise notre organisation et les membres qui la composent.&nbsp; Il est donc imp&eacute;ratif que tous les membres, sans exception, s'y conforment, et ce en tout temps, que ce soit pendant un encadrement ou une sortie r&eacute;guli&egrave;re du club.
	</p>
	<p><br>
		<a name="Reglement"></a><b>R&egrave;glements des membres</b></p>
	<p>Les membres doivent payer leur cotisation annuelle, afin de demeurer membre en r&egrave;gle. Le Club recommande &agrave; tous ses membres exp&eacute;riment&eacute;s de suivre, &agrave; tous les 2 ans, les cours de secourisme ainsi que le cours de m&eacute;canique.<br>
		Les&nbsp;&nbsp; nouveaux&nbsp;&nbsp; membres&nbsp;&nbsp; n'ayant&nbsp;&nbsp; pas&nbsp;&nbsp; suivi &nbsp;la &nbsp;formation &laquo;&nbsp;S&eacute;curit&eacute; et encadrement&nbsp;&raquo; des Sentinelles ne pourront pas encadrer.&nbsp; Ces&nbsp;membres sont&nbsp;toutefois&nbsp;les bienvenus pour rouler dans les randonn&eacute;es.&nbsp; Ils devront le faire, &agrave; l'arri&egrave;re des pelotons, jusqu&rsquo;&agrave; leur formation pour observer les encadreurs d'exp&eacute;rience.<br>
		Il est obligatoirement de porter le maillot des Sentinelles et le casque lors de tous les encadrements.&nbsp; Il est aussi recommand&eacute; de les porter lors des sorties du Club.<br>
		Les membres doivent respecter le maillot des Sentinelles en tout temps lorsque vous le portez (pas de <em>Jeans</em>, pas de sandales, fermeture &eacute;clair relev&eacute;e).<br>
		Les membres doivent especter les feux de circulation, demeurer courtois avec les automobilistes et respecter le code de la s&eacute;curit&eacute; routi&egrave;re.<br>
		Afin d&rsquo;&eacute;viter les chutes, il est strictement d&eacute;fendu &agrave; tout membre de pousser ou toucher un autre cycliste, qu'il s'agisse d'un participant ou d'un autre encadreur.<br>
		Il est interdit d&rsquo;avoir une b&eacute;quille install&eacute;e &agrave; l&rsquo;arri&egrave;re du v&eacute;lo (afin d&rsquo;&eacute;viter que la roue avant du cycliste qui vous suit s&rsquo;y accroche).<br>
		Le port des sacoches &agrave; v&eacute;lo lat&eacute;rales est interdit lors des encadrements afin d'&eacute;viter les accrochages.&nbsp; Il est permis d&rsquo;avoir une sacoche sous la selle ou au-dessus de la roue arri&egrave;re sur un support.</p>
	<p><a name="ConsEnc"></a><b>Consignes de s&eacute;curit&eacute; lors des encadrements</b></p>
	<tr>
		<td width="43" valign="top"></td>
		Lorsqu'un encadreur est responsable d'un peloton, il doit voir &agrave; ce qu'aucun participant ne soit laiss&eacute; seul une fois le camion balai pass&eacute;.<br>
		Si l'on d&eacute;sire parler &agrave; l&rsquo;encadreur devant nous, on acc&eacute;l&egrave;re pour le rejoindre en restant derri&egrave;re lui.&nbsp; Apr&egrave;s la discussion, on reprend notre position le plus rapidement possible.<br>
		Les encadreurs doivent indiquer les obstacles &agrave; l&rsquo;avance en les criant et en les indiquant de la main.&nbsp; Ils encouragent les participants &agrave; passer ces messages.<br>
		Lors d'un encadrement, l'encadreur doit aviser tout cycliste roulant <u>&agrave; plus de 20 m&egrave;tres &agrave; l'arri&egrave;re du peloton</u> qu'il doit embarquer dans le camion, faute de quoi nous ne sommes plus responsables de lui.&nbsp; Ceci &eacute;vite qu&rsquo;un v&eacute;hicule s&rsquo;ins&egrave;re &agrave; l&rsquo;int&eacute;rieur du peloton et met en priorit&eacute; la s&eacute;curit&eacute; du groupe avant celle d&rsquo;un seul participant.<br>
		Lors des mont&eacute;es, les encadreurs ouvreurs acc&eacute;l&egrave;rent la vitesse afin d&rsquo;&eacute;viter les &laquo;&nbsp;barrages&nbsp;&raquo;&nbsp;de cyclistes.&nbsp; Imm&eacute;diatement apr&egrave;s les mont&eacute;es, l'encadreur &agrave; la t&ecirc;te du peloton doit ralentir suffisamment le rythme afin de permettre au peloton de grimper tout en demeurant regroup&eacute;.&nbsp; Arr&ecirc;ter le peloton au besoin en haut de la c&ocirc;te.<br>
		Tout incident lors d'un encadrement doit &ecirc;tre rapport&eacute; au responsable de peloton, sans faute et le plus rapidement possible, afin de produire un rapport d'incident ou d'accident selon les besoins.<br>
		Durant une randonn&eacute;e, les encadreurs doivent &ecirc;tre alertes et &agrave; l'&eacute;coute des participants.&nbsp; Il est important d'&eacute;changer avec les participants des randonn&eacute;es au sujet de la s&eacute;curit&eacute; ou sur un autre sujet afin de d&eacute;tendre l'atmosph&egrave;re.<br>
		C'est la responsabilit&eacute; et le devoir des encadreurs de v&eacute;rifier visuellement l'&eacute;tat des v&eacute;los et l&rsquo;&eacute;quipement des participants avant le d&eacute;part d'une randonn&eacute;e (pneus, hauteur de la selle, casque, habillement ad&eacute;quat, etc).<br>
		Il est interdit aux participants d&rsquo;utiliser des poign&eacute;es de contre-la-montre.&nbsp; Les v&eacute;los adapt&eacute;s doivent rester &agrave; l&rsquo;arri&egrave;re des pelotons.<br>
		Chaque encadreur doit respecter les consignes de l'encadreur responsable du peloton. En cas de diff&eacute;rend, se r&eacute;f&eacute;rer au responsable de l'activit&eacute;.<br>
		Un encadreur qui roule &agrave; c&ocirc;t&eacute; du peloton (lorsqu&rsquo;il est en mouvement) doit &eacute;viter de s&rsquo;arr&ecirc;ter dans la file des encadreurs.<br>
		Si un encadreur doit s'arr&ecirc;ter pour aider un participant en difficult&eacute;, il doit se tasser &agrave; la droite de la route avec ce cycliste.<br>
		Les encadreurs doivent s'assurer que les cyclistes roulent &agrave; 3 de largeur maximum en tout temps.&nbsp; Si la voie est &eacute;troite, les encadreurs peuvent demander aux participants de rouler au plus 2 cyclistes de largeur afin de laisser suffisamment de place &agrave; la gauche pour les encadreurs.<br>
		Les encadreurs devant d&eacute;passer d'autres encadreurs de la file lat&eacute;rale doivent toujours le faire par la gauche.<br>
		Les encadreurs ne doivent jamais rouler &agrave; gauche des lignes centrales jaunes pour leur propre s&eacute;curit&eacute;.<br>
		Lorsqu&rsquo;un encadreur en d&eacute;passe un autre, il doit l&rsquo;informer de son intention (ex : &quot;Je d&eacute;passe &agrave; gauche&quot;) et l&rsquo;autre doit r&eacute;pondre (ex&nbsp;: &quot;C&rsquo;est beau&quot; ou &quot;OK&quot;).<br>
		Les encadreurs d&rsquo;exp&eacute;rience sont encourag&eacute;s &agrave; aider les encadreurs responsables ou d&rsquo;autres encadreurs dans le besoin (ex&nbsp;: &laquo;&nbsp;Je vais t&rsquo;aider&hellip;&nbsp;&raquo;).&nbsp; Les informer de ce que vous ferez pour les aider.&nbsp; Ces encadreurs exp&eacute;riment&eacute;s sont aussi autoris&eacute;s &agrave; prendre des initiatives en cas de force majeure (ex&nbsp;: l&rsquo;encadreur responsable qui n&rsquo;est pas inform&eacute; d&rsquo;une situation mettant en cause la s&eacute;curit&eacute; des cyclistes).<br>
		Les encadreurs positionn&eacute;s aux intersections devant le peloton (ex : li&egrave;vres) doivent se placer sur les lignes centrales jaunes.<br>
		Les encadreurs responsables de pelotons (et leurs adjoints)&nbsp;confient&nbsp;des t&acirc;ches strat&eacute;giques&nbsp;seulement aux encadreurs exp&eacute;riment&eacute;s.&nbsp; (Ex&nbsp;: li&egrave;vres aux intersections).<br>
		Les encadreurs responsables de randonn&eacute;es choisissent la technique d&rsquo;encadrement appropri&eacute;e &agrave; la randonn&eacute;e et aux circonstances (voir section suivante).&nbsp; Avant le d&eacute;part, ils en informent&nbsp;les encadreurs lors des consignes de s&eacute;curit&eacute;.<br>
		Les encadreurs s&rsquo;assurent que les participants ne font pas de louvoiement &agrave; l&rsquo;int&eacute;rieur du peloton.</p></td></tr>
	<br>
	<p><a name="Technique"></a><b>Techniques d&rsquo;encadrements</b></p>
	<ul>
		<li><u><a href="tech_enc_rand_pop.pdf"><font color="red">Encadrement en randonn&eacute;es populaires</font></a> </u><br>
			(ex : Randonn&eacute;e Tanguay)
		<li><u><a href="tech_enc_peloton_file_ind.pdf"><font color="red">Encadrement en peloton ou en file indienne</font></a> </u><br>
			(ex : Randonn&eacute;e de Lotbini&egrave;re)
	</ul>
	<br>
	<p><a name="ConsSortie"></a><b>Consignes de s&eacute;curit&eacute; lors des sorties</b></p>
	<tr>
		<td width="43" valign="top">La vitesse moyenne d'un peloton &agrave; la fin d'une sortie doit &ecirc;tre &agrave; plus ou moins 1 km/h de la vitesse moyenne pr&eacute;vue autant que possible (ex&nbsp;: conditions climatiques).<br>
		En mont&eacute;e durant les sorties, les cyclistes les plus lents gardent la droite afin de laisser le champ libre aux plus rapides.&nbsp; Le peloton se regroupe au sommet de la mont&eacute;e afin d'attendre les cyclistes qui sont derri&egrave;re eux.<br>
		Durant les sorties, les d&eacute;placements se font &agrave; la file indienne.<br>
		Pour passer le relais, on tourne une main au-dessus de la t&ecirc;te en criant &quot;Relais&quot;.&nbsp; Les relais doivent s&rsquo;effectuer dans des endroits s&eacute;curitaires (ex&nbsp;: pas dans une courbe).<br>
		Pour entrer ou sortir du peloton, on pointe &agrave; gauche ou &agrave; droite avec le doigt.<br>
		Ne pas effectuer de d&eacute;passement lors des descentes.</p></td></tr>
	</table></p></div>

						