
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>La section des membres des Sentinelles de la Route</h1>
						
						<div class="textes">
							<p>R&eacute;unions C.A.<br>
		Changement addr.<br>
		Liste des membres<br>
		Escomptes</p>
	<p>Section en d&eacute;veloppement...<br>
		<br>
		<img src="images/defi_velo_desj.jpg" alt="" width="500" height="300" border="0"></p>
</div>