
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES SORTIES DE LA SAISON 2010</h1><br>
						<table width="175" border="0" cellspacing="2" cellpadding="2" align="right" height="20">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="depart.php">LES LIEUX DE D&Eacute;PART</a></font></td>
			</tr>
		</table>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sorties.php">MAI </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuillet.php">JUILLET</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesaout.php">AO&Ucirc;T</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesseptembre.php">SEPTEMBRE</a></font></td>
			</tr>
		</table>		
						<div class="textes">
							<br>

			<body bgcolor="#FFCC33">
		<!-- Start Calendar, juin 2010 -->
<p align="center"><font color="#ed1b24" size="5" face="Arial">Sorties de JUIN 2010</font></p>
<table width="100%" border="1" cellspacing="0" bordercolor="#000000" cellpadding="4">
  <tr>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
    <td valign="top" colspan="2"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial">1<br>
						Jardin zoologique 4&nbsp;<br>
						<a href="sorties/jardin_zoologique4.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							36,3 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">2<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">3<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">4<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial">5<br>
						L&eacute;vis 1&nbsp;<br>
						<a href="sorties/Levis1.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							91,8 km</a></font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">6<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial">8<br>
						Ste-Foy 1&nbsp;<br>
						<a href="sorties/Ste-Foy1.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							42,5 km&nbsp;</a></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">11<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial">12<br>
						Ste-Anne-de-la-P&eacute;rade<br>
						<a href="http://maps.google.ca/maps?f=q&source=s_q&hl=fr&geocode=&q=1201,+boul.+Duplessis,+ancienne-lorette&sll=45.513805,-73.615952&sspn=0.172255,0.370445&dirflg=r&ttype=dep&date=10%2F06%2F10&time=09:21&noexp=0&noal=0&sort=&ie=UTF8&hq=1201,+boul.+Duplessis,&hnear=L%27Ancienne-Lorette,+QC&z=14'" target="_blank">(D&eacute;part Loblaws Duplessis &agrave; 8h30)</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">13<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">14<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial">15<br>
						Carrefour Neufchatel 3&nbsp;<br>
						<a href="sorties/CarrefourNeufchatel3.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							44,3 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">17<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">18<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">19<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">20<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">21<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial">22<br>
						Carrefour Neufchatel 2&nbsp;<br>
						<a href="sorties/CarrefourNeufchatel2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							45,8 km&nbsp;</a></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">23<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">24<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">25<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font size="3" color="#000000" face="Arial">26<br>
						Charny 3,3&nbsp;<br>
						<a href="sorties/Charny3.3.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							126,7 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">27<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">28<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial">29<br>
						Jardin zoologique 2&nbsp;<br>
						<a href="sorties/JardinZoologique2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							47,4 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">30<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" colspan="3"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
  </tr>
</table>
<!-- End Calendar, mai 2010 -->

</body>
</html>
	</p>
		</div>