
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES SORTIES DE LA SAISON 2010</h1><br>
						<table width="175" border="0" cellspacing="2" cellpadding="2" align="right" height="20">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="depart.php">LES LIEUX DE D&Eacute;PART</a></font></td>
			</tr>
		</table>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sorties.php">MAI </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuin.php">JUIN</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuillet.php">JUILLET</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesaout.php">AO&Ucirc;T</a></font></td>
			</tr>
		</table>		
						<div class="textes">
							<br>

			<body bgcolor="#FFCC33">
		<!-- Start Calendar, septembre 2010 -->
<p align="center"><font color="#ed1b24" size="5" face="Arial">Sorties de SEPTEMBRE 2010</font></p>
<table width="100%" border="1" cellspacing="0" bordercolor="#000000" cellpadding="4">
  <tr>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
    <td valign="top" colspan="3"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">1<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">2<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">3<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>4</strong><br>
						<a href="sorties/quebec_Donnaconna.pdf" target="_blank">
						Qu&eacute;bec/<br>
							Donnaconna&nbsp;<br>
							91,1 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">5<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">6<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">8<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ffffcc" align="left"><font color="#000000" size="3" face="Arial">11<br>
						&nbsp;&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">12<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">13<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>14</strong><br>
						Carrefour Neufchatel <br>
						(Trajet&nbsp;libre)<br>
						&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">15<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">17<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>18</strong><br>
						<a href="sorties/quebec_Neuville.pdf" target="_blank">
						Qu&eacute;bec/<br>
							Neufville&nbsp;<br>
							68,2 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">19<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">20<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>21</strong><br>
						Jardin zoologique<br>
						(Trajet&nbsp;libre)</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">22<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">23<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">24<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>25</strong><br>
						&Agrave; d&eacute;terminer&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">26<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">27<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>28</strong><br>
						Canac Marquis<br>
						(Trajet&nbsp;libre)</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">29<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">30<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" colspan="2"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
  </tr>
</table>
<!-- End Calendar, septembre 2010 -->

</body>
</html>
	</p>
		</div>