
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES SORTIES DE LA SAISON 2010</h1><br>
						<table width="175" border="0" cellspacing="2" cellpadding="2" align="right" height="20">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="depart.php">LES LIEUX DE D&Eacute;PART</a></font></td>
			</tr>
		</table>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuin.php">JUIN </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuillet.php">JUILLET</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesaout.php">AO&Ucirc;T</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesseptembre.php">SEPTEMBRE</a></font></td>
			</tr>
		</table>		
						<div class="textes">
						<p>Le départ pour les sorties du mardi se fait à 18h30.
						Le départ pour les sorties du samedi se fait à 10h00 pour les mois de mai et de septembre et à 9h00 pour les mois de juin, juillet et août.
							<br>

			<body bgcolor="#FFCC33">
		<!-- Start Calendar, mai 2010 -->
		<p align="center"><font color="#ed1b24" size="5" face="Arial">Sorties de MAI 2010</font></p>
		<table width="100%" border="1" cellspacing="0" bordercolor="#FFCC33" cellpadding="4">
  <tr>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
    <td valign="top" colspan="6"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">1<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr height="90">
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial">2<br><br></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial">3<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial"><strong>4</strong><br>
						Canac Marquis<br>
						<a href="sorties/Canac2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							34.6 km</a><br>
					</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font size="3" color="#000000" face="Arial">5&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial">6<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%" height="90"><font color="#000000" size="3" face="Arial">8<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font size="3" color="#000000" face="Arial"><strong>11</strong><br>
						Carefour neufchatel<br>
						<a href="sorties/CarrefourNeufchatel4.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							39.9 km<br>
						</a></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">12<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">13<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">14<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial"><strong>15</strong><br>
						
						St-Nicolas<br>
						<a href="sorties/StNicolas1.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							80,4 km</a></font>
					<p><font color="#000000" size="3" face="Arial"><a href="javascript:void window.open('http://maps.google.ca/maps?ll=46.71671,-71.296248&spn=0.009062,0.016415&t=h&z=16','popup','Width=780,height=580,scrollbars=1,resizable=1,')">Lieu de d&eacute;part sur&nbsp; Google map</a></font></p>
				</td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">17<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial"><strong>18</strong><br>
						
						St-Foy <br>
						<a href="sorties/Ste-Foy3.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
								33.3 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">19<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">20<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">21<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial"><strong>22</strong><br>
						
						Loretteville<br>
						<a href="sorties/Loretteville1.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							91 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">23<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">24<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial"><strong>25</strong><br>
						
						Jardin zoologique 3<br>
						<a href="sorties/jardin_zoologique3.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							32.9 km&nbsp;</a></font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">26<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">27<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">28<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left" width="14%"><font color="#000000" size="3" face="Arial"><strong>29</strong><br>
						
						Charny<br>
						<a href="sorties/Charny3.pdf" target="_blank">T&eacute;l&eacute;charger le trajet<br>
							91,4 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">30<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left" width="14%"><font color="#000000" size="3" face="Arial">31<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" colspan="5"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
  </tr>
</table>
<!-- End Calendar, mai 2010 -->

</body>
</html>
	</p>
		</div>