
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>LES SORTIES DE LA SAISON 2010</h1><br>
						<table width="175" border="0" cellspacing="2" cellpadding="2" align="right" height="20">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="depart.php">LES LIEUX DE D&Eacute;PART</a></font></td>
			</tr>
		</table>
						<table width="200" border="0" cellspacing="2" cellpadding="2">
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sorties.php">MAI </a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesjuin.php">JUIN</a></font></td>
			</tr>
			<tr height="20">
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesaout.php">AO&Ucirc;T</a></font></td>
				<td align="center" valign="middle" bgcolor="red" width="100" height="20"><font color="#ed1b24" size="4" face="Arial"><a href="sortiesseptembre.php">SEPTEMBRE</a></font></td>
			</tr>
		</table>		
						<div class="textes">
							<br>

			<body bgcolor="#FFCC33">
		<!-- Start Calendar, juillet 2010 -->
<p align="center"><font color="#ed1b24" size="5" face="Arial">Sorties de JUILLET 2010</font></p>
<table width="100%" border="1" cellspacing="0" bordercolor="#000000" cellpadding="4">
  <tr>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">dimanche</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">lundi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mardi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">mercredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">jeudi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">vendredi</font></td>
    <td width="14%" align="center" valign="middle" bgcolor="#000000"><font color="#FFFFFF" size="3" face="Arial">samedi</font></td>
  </tr><tr>
    <td valign="top" colspan="4"><font size="3" face="Arial">&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">1<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">2<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>3</strong><br>
						Charny 3.2&nbsp;<a href="sorties/ValBelair1.pdf" target="_blank"><br>
						</a><a href="sorties/charny_3.2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							109,9 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">4<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">5<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>6</strong><br>
						Limoilou Ch&acirc;teau-Richer&nbsp;<br>
						<a href="sorties/limoilou_chateau-richer.pdf" target="_blank">T&eacute;l&eacute;chargez le trajet<br>
							51 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">7<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">8<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">9<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">10<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">11<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">12<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>13</strong><br>
						Michel Labadie 2&nbsp;<br>
						<a href="sorties/MichelLabadie2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							52,2 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">14<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">15<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">16<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>17</strong><br>
						Lac Sept-&Icirc;les<br>
						(Rte 358, 354, 367)&nbsp;<br>
						<a href="sorties/lac_sept_iles.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							127 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">18<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">19<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>20</strong><br>
						Carrefour Neufchatel 1&nbsp;<br>
						<a href="sorties/CarrefourNeufchatel1et2.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							56,7 km</a>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">21<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">22<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">23<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>24</strong><br>
						L&eacute;vis/<br>
						St-Vallier&nbsp;<br>
						<a href="sorties/levis_st_vallier.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
								92 km</a>&nbsp;</font></td>
  </tr><tr>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">25<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">26<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>27</strong><br>
						Jardin zoologique<br>
						C&ocirc;te du calvair&nbsp;<br>
						<a href="sorties/jardin_zool_cote_calvaire.pdf" target="_blank">T&eacute;l&eacute;charger le trajet&nbsp;<br>
							45 km</a>&nbsp;&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">28<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">29<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#FFFFCC" align="left"><font color="#000000" size="3" face="Arial">30<br>
						&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;</font></td>
    <td valign="top" bgcolor="#ed1b24" align="left"><font color="#000000" size="3" face="Arial"><strong>31</strong><br>
						Tour de l&rsquo;&Icirc;le<br>
						d&rsquo;Orl&eacute;ans&nbsp;<a href="sorties/ValBelair1.pdf" target="_blank"><br>
						</a>67 km&nbsp;</font></td>
  </tr>
</table>
<!-- End Calendar, juillet 2010 -->

</body>
</html>
	</p>
		</div>