
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Vid&eacute;os des encadrements des Sentinelles de la Route</h1>
						
					<div class="textes">
							<p>
	<p align="left" class="style1"><a href="http://www.youtube.com/watch?v=cb8H5MKcEc4" target="_blank"><font color="red">Tour de Beauce (premi&egrave;re partie)</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=tAuoVctd6R8" target="_blank"><font color="red">Tour de Beauce (deuxi&egrave;me partie)</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=3LmkTSNSkng    " target="_blank"><font color="red">Randonn&eacute;e Tanguay</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=UxS8Us1mjzQ" target="_blank"><font color="red">Cyclo-d&eacute;fi contre le cancer</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=61MHLL3GIdE" target="_blank"><font color="red">Randonn&eacute;e de la Pr&eacute;vention du suicide</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=F_E_kiEAmdY" target="_blank"><font color="red">Festival Lorettain</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=yql6_weLnKA" target="_blank"><font color="red">Cyclo-d&eacute;fi de Qu&eacute;bec</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=b3pBmlUO1jU" target="_blank"><font color="red">Vir&eacute;e-v&eacute;lo St-Henri (Implant cochl&eacute;aire)</font></a></p>
	<p><a href="http://www.youtube.com/watch?v=FL9S1OPTRnE" target="_blank"><font color="red">Marathon Des Deux Rives, Levis Qu&eacute;bec, 29-ao&ucirc;t, 2010</font></a></p>
	<table width="64" border="0" cellspacing="0" cellpadding="0" align="left">
		<tr>
			<td><img src="images/video.jpg" alt="" width="550" height="346" border="0"></td>
		</tr>
	</table>
	<p></p>
</div>