
<link href="../style.css" rel="stylesheet" media="screen">
						<h1>Les responsables du site des Sentinelles de la Route</h1>
						
						<div class="textes">
							<p>Si vous avez des commentaires positifs ou constructifs sur le contenu des pages et la pr&eacute;sentation de ce site Internet, n&rsquo;h&eacute;sitez pas &agrave; nous contacter !<br>
        <br>Webmestre : <a href="mailto:jonathan.breton@gmail.com?subject=Courriel%20au%20webmestre%20du%20site%20%20des%20Sentinelles%20"><strong><font color="red">Jonathan Breton</font> </strong></a></font><br>
		Concepteur : <a href="mailto:rectoverso@videotron.qc.ca?subject=Courriel%20au%20webmestre%20du%20site%20%20des%20Sentinelles%20"><strong><font color="red">R&eacute;jean Cloutier</font> </strong></a></font><br>
     </p>
	<table width="64" border="0" cellspacing="0" cellpadding="0" align="center">
		<tr>
			<td><img src="images/promo_sentinelles.jpg" alt="" width="700" height="487" border="0"></td>
		</tr>
	</table>
	<p align="center"></p>
</div>